/**
 * TPA — DOCX redline exporter.
 *
 * Produces a Word document with formal track-change-style markup:
 *   - Cover page: counterparty / agreement / verdict / risk score / summary.
 *   - Per-clause sections in playbook order:
 *       • Verdict pill (Accept / Amend / Reject / Missing) in colour.
 *       • Original counterparty wording (red strikethrough = deletion).
 *       • Proposed redline (blue underline = insertion) — user override
 *         takes precedence over AI suggestion.
 *       • Rationale paragraph.
 *
 * The format is intentionally a Word redline that any counterparty lawyer
 * can open and respond to. We do NOT inject Word-native revision XML; we
 * use bold-coloured runs because that is more universally readable across
 * Word, Pages, Google Docs, and PDF preview.
 */
import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  ShadingType,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx';

type Verdict = 'accept' | 'amend' | 'reject' | 'missing' | 'info';

export interface RedlineFinding {
  clauseTitle: string;
  displayOrder: number;
  extractedText: string | null;
  extractedLocation: string | null;
  aiVerdict: Verdict;
  userVerdict: Verdict | null;
  aiRationale: string | null;
  aiSuggestedRedline: string | null;
  userRedline: string | null;
  userNotes: string | null;
  playbookStandard?: string | null;
  playbookFallback?: string | null;
}

export interface RedlineReviewHeader {
  referenceCode: string;
  counterpartyName: string;
  agreementTitle: string;
  agreementType: string;
  overallVerdict: 'accept' | 'amend' | 'reject' | null;
  overallRisk: 'low' | 'medium' | 'high' | 'critical' | null;
  riskScore: number | null;
  executiveSummary: string | null;
  acceptCount: number;
  amendCount: number;
  rejectCount: number;
  playbookNameEn?: string | null;
  generatedAt: Date;
  generatedByName: string;
}

const COLOR = {
  red: 'B91C1C',       // deletion
  blue: '1D4ED8',      // insertion (proposed redline)
  green: '047857',     // accepted / OK
  amber: 'B45309',     // amend warning
  gray: '4B5563',
  black: '111827',
  surfaceMute: 'F3F4F6',
};

function verdictLabel(v: Verdict | null): string {
  switch (v) {
    case 'accept':
      return 'ACCEPT';
    case 'amend':
      return 'AMEND';
    case 'reject':
      return 'REJECT';
    case 'missing':
      return 'MISSING';
    case 'info':
      return 'INFO';
    default:
      return 'PENDING';
  }
}

function verdictColor(v: Verdict | null): string {
  switch (v) {
    case 'accept':
      return COLOR.green;
    case 'amend':
      return COLOR.amber;
    case 'reject':
      return COLOR.red;
    case 'missing':
      return COLOR.gray;
    default:
      return COLOR.black;
  }
}

function makeHeader(header: RedlineReviewHeader): Paragraph[] {
  const paras: Paragraph[] = [];
  paras.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 240 },
      children: [
        new TextRun({
          text: 'CONFIDENTIAL — ADNOC REDLINE',
          bold: true,
          size: 28,
          color: COLOR.red,
        }),
      ],
    }),
  );
  paras.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      heading: HeadingLevel.HEADING_2,
      spacing: { after: 360 },
      children: [
        new TextRun({ text: header.agreementTitle, bold: true, size: 26, color: COLOR.black }),
      ],
    }),
  );

  // Metadata table
  const metaRows: [string, string][] = [
    ['Reference', header.referenceCode],
    ['Counterparty', header.counterpartyName],
    ['Agreement type', header.agreementType.toUpperCase()],
    ['Playbook', header.playbookNameEn ?? 'ADNOC standard'],
    ['Overall verdict', verdictLabel(header.overallVerdict)],
    ['Overall risk', (header.overallRisk ?? 'unknown').toUpperCase()],
    ['Risk score', header.riskScore !== null ? `${header.riskScore} / 100` : '—'],
    [
      'Findings',
      `${header.acceptCount} accept · ${header.amendCount} amend · ${header.rejectCount} reject`,
    ],
    ['Generated', header.generatedAt.toISOString().slice(0, 16).replace('T', ' ') + ' UTC'],
    ['Generated by', header.generatedByName],
  ];
  paras.push(
    new Paragraph({
      spacing: { after: 240 },
      children: [
        new TextRun({
          text: makeMetaText(metaRows),
          size: 22,
          color: COLOR.gray,
        }),
      ],
    }),
  );

  if (header.executiveSummary) {
    paras.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_3,
        spacing: { before: 240, after: 120 },
        children: [
          new TextRun({ text: 'Executive summary', bold: true, size: 24, color: COLOR.black }),
        ],
      }),
    );
    for (const para of splitParas(header.executiveSummary)) {
      paras.push(
        new Paragraph({
          spacing: { after: 120 },
          children: [new TextRun({ text: para, size: 22, color: COLOR.black })],
        }),
      );
    }
  }

  paras.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_3,
      pageBreakBefore: true,
      spacing: { after: 240 },
      children: [
        new TextRun({ text: 'Clause-by-clause redline', bold: true, size: 26, color: COLOR.black }),
      ],
    }),
  );

  return paras;
}

function makeMetaText(rows: [string, string][]): string {
  return rows.map(([k, v]) => `${k}: ${v}`).join('   |   ');
}

function makeFindingSection(f: RedlineFinding, idx: number): Paragraph[] {
  const paras: Paragraph[] = [];
  const verdict = (f.userVerdict ?? f.aiVerdict) as Verdict;
  const redline = f.userRedline ?? f.aiSuggestedRedline ?? null;
  const verdictBg = verdictColor(verdict);

  // Clause header pill + title
  paras.push(
    new Paragraph({
      spacing: { before: 360, after: 60 },
      children: [
        new TextRun({
          text: `  ${verdictLabel(verdict)}  `,
          bold: true,
          size: 18,
          color: 'FFFFFF',
          shading: { type: ShadingType.CLEAR, fill: verdictBg, color: 'auto' },
        }),
        new TextRun({ text: `   ${idx + 1}. ${f.clauseTitle}`, bold: true, size: 26, color: COLOR.black }),
      ],
    }),
  );

  if (f.extractedLocation) {
    paras.push(
      new Paragraph({
        spacing: { after: 120 },
        children: [
          new TextRun({
            text: `Source: ${f.extractedLocation}`,
            italics: true,
            size: 18,
            color: COLOR.gray,
          }),
        ],
      }),
    );
  }

  // Counterparty wording
  // accept/info → keep, plain
  // amend      → strikethrough (deletion) + proposed redline below
  // reject     → strikethrough (deletion) + "Recommend deletion" note (NO redline)
  // missing    → no extracted text; show insertion below
  if (f.extractedText) {
    const labelText =
      verdict === 'accept' || verdict === 'info'
        ? 'Counterparty wording (kept):'
        : verdict === 'reject'
          ? 'Counterparty wording (recommend deletion):'
          : 'Counterparty wording (proposed deletion):';
    const labelColor = verdict === 'accept' || verdict === 'info' ? COLOR.green : COLOR.red;
    paras.push(
      new Paragraph({
        spacing: { before: 120, after: 60 },
        children: [new TextRun({ text: labelText, bold: true, size: 20, color: labelColor })],
      }),
    );
    paras.push(
      new Paragraph({
        spacing: { after: 120 },
        indent: { left: 360 },
        children: [
          new TextRun({
            text: f.extractedText,
            size: 22,
            color: verdict === 'accept' || verdict === 'info' ? COLOR.black : COLOR.red,
            strike: verdict === 'amend' || verdict === 'reject',
          }),
        ],
      }),
    );
  } else if (verdict === 'missing') {
    paras.push(
      new Paragraph({
        spacing: { before: 120, after: 60 },
        children: [
          new TextRun({
            text: '— No corresponding clause found in counterparty agreement —',
            italics: true,
            size: 20,
            color: COLOR.gray,
          }),
        ],
      }),
    );
  }

  // Insertion / redline
  //   - amend   → "Proposed redline" (replacement language)
  //   - missing → "Proposed insertion (ADNOC standard wording)"
  //   - reject  → NO replacement; show a note that ADNOC asks to delete the clause
  if (verdict === 'reject') {
    paras.push(
      new Paragraph({
        spacing: { before: 120, after: 120 },
        indent: { left: 360 },
        children: [
          new TextRun({
            text:
              'ADNOC requests this clause be deleted in its entirety. No replacement language is offered as part of this redline; the topic will be addressed separately (or its absence is acceptable to ADNOC).',
            italics: true,
            size: 20,
            color: COLOR.gray,
          }),
        ],
      }),
    );
  } else if (redline && (verdict === 'amend' || verdict === 'missing')) {
    paras.push(
      new Paragraph({
        spacing: { before: 120, after: 60 },
        children: [
          new TextRun({
            text:
              verdict === 'missing'
                ? 'Proposed insertion (ADNOC standard wording):'
                : 'Proposed redline:',
            bold: true,
            size: 20,
            color: COLOR.blue,
          }),
        ],
      }),
    );
    for (const para of splitParas(redline)) {
      paras.push(
        new Paragraph({
          spacing: { after: 80 },
          indent: { left: 360 },
          children: [
            new TextRun({
              text: para,
              size: 22,
              color: COLOR.blue,
              underline: { type: 'single', color: COLOR.blue },
            }),
          ],
        }),
      );
    }
  }

  // Rationale + notes
  if (f.aiRationale) {
    paras.push(
      new Paragraph({
        spacing: { before: 120, after: 60 },
        children: [
          new TextRun({ text: 'Rationale: ', bold: true, size: 18, color: COLOR.gray }),
          new TextRun({ text: f.aiRationale, italics: true, size: 18, color: COLOR.gray }),
        ],
      }),
    );
  }
  if (f.userNotes) {
    paras.push(
      new Paragraph({
        spacing: { after: 120 },
        children: [
          new TextRun({ text: 'Counsel note: ', bold: true, size: 18, color: COLOR.gray }),
          new TextRun({ text: f.userNotes, italics: true, size: 18, color: COLOR.gray }),
        ],
      }),
    );
  }

  // Visual divider
  paras.push(
    new Paragraph({
      border: {
        bottom: { color: COLOR.surfaceMute, space: 1, style: BorderStyle.SINGLE, size: 6 },
      },
      spacing: { before: 120, after: 240 },
      children: [],
    }),
  );

  return paras;
}

function splitParas(text: string): string[] {
  return text
    .split(/\n{2,}|\r?\n/)
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

// ----------------------------------------------------------------
// Public API
// ----------------------------------------------------------------

export async function buildRedlineDocx(args: {
  header: RedlineReviewHeader;
  findings: RedlineFinding[];
}): Promise<{ buffer: Buffer; fileName: string }> {
  const sortedFindings = [...args.findings].sort((a, b) => a.displayOrder - b.displayOrder);

  const children: (Paragraph | Table)[] = [];
  children.push(...makeHeader(args.header));
  sortedFindings.forEach((f, i) => {
    children.push(...makeFindingSection(f, i));
  });

  // Footer-ish closing paragraph
  children.push(
    new Paragraph({
      pageBreakBefore: true,
      alignment: AlignmentType.CENTER,
      spacing: { before: 240, after: 120 },
      children: [
        new TextRun({
          text: 'This redline reflects ADNOC\'s position on the above clauses. We look forward to your response.',
          italics: true,
          size: 20,
          color: COLOR.gray,
        }),
      ],
    }),
  );
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: 'ADNOC Legal Affairs Division',
          bold: true,
          size: 22,
          color: COLOR.black,
        }),
      ],
    }),
  );

  const doc = new Document({
    creator: 'ADNOC Musanad Contracts Hub',
    title: `Redline — ${args.header.referenceCode}`,
    description: `Third-party agreement redline against ${args.header.playbookNameEn ?? 'ADNOC playbook'}`,
    sections: [
      {
        properties: {},
        children,
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  const safeName =
    `Redline_${args.header.referenceCode}_${args.header.counterpartyName}`
      .replace(/[^a-zA-Z0-9_-]+/g, '_')
      .slice(0, 80) + '.docx';
  return { buffer, fileName: safeName };
}
