-- ============================================================================
-- 096_pa_user_admin_actions.sql
-- ============================================================================
-- Module:    R-PA2 (Platform Admin parity — /admin/users row actions)
-- Owner:     Lovable Modernization Agent — Platform Admin parity
-- Depends:   001 (fn_user_update, fn_user_get_by_id, "user", role tables).
-- ----------------------------------------------------------------------------
-- Closes the BE gaps for the four /admin/users row actions:
--   * Invite user          — existing POST /api/v1/users via fn_user_create.
--   * Change role          — existing PUT /api/v1/users/:id (roleId).
--   * Suspend / reactivate — extends fn_user_update so PUT /api/v1/users/:id
--                            accepts { isActive }. Without this, suspend
--                            requires DELETE /:id and reactivate has no path.
--   * Reset password       — new fn_user_password_reset(p_id, p_pw_hash,
--                            p_actor) — controller hashes the plaintext
--                            generated by the admin.
--
-- Stage 2 standards observed:
--   S2-21 — REVOKE FROM PUBLIC + GRANT EXECUTE TO neondb_owner.
--   S2-22 — column existence verified (user.is_active + user.password_hash).
--   Self-protection — admin cannot suspend OR reset their own password
--   (mirrors fn_user_delete's existing `cannot deactivate your own account`).
-- ============================================================================

BEGIN;

-- ──────────────────────────────────────────────────────────────────────────
-- 1. fn_user_update — add isActive support
-- ──────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION fn_user_update(p_id BIGINT, p_data JSONB, p_actor_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
  v_result    JSONB;
  v_new_email TEXT;
  v_role_id   BIGINT;
  v_is_active BOOLEAN;
BEGIN
  IF p_id IS NULL THEN
    RAISE EXCEPTION 'fn_user_update: p_id is required';
  END IF;
  IF p_data IS NULL THEN
    RAISE EXCEPTION 'fn_user_update: p_data is required';
  END IF;

  -- Existence (no longer requires is_active=true — admin needs to
  -- reactivate suspended users via this fn).
  IF NOT EXISTS (SELECT 1 FROM "user" WHERE id = p_id) THEN
    RAISE EXCEPTION 'fn_user_update: user not found';
  END IF;

  -- Email uniqueness (only if email is being changed)
  IF p_data ? 'email' AND p_data->>'email' IS NOT NULL AND p_data->>'email' <> '' THEN
    v_new_email := LOWER(p_data->>'email');
    IF EXISTS (
      SELECT 1 FROM "user" WHERE LOWER(email) = v_new_email AND id <> p_id
    ) THEN
      RAISE EXCEPTION 'fn_user_update: email already in use';
    END IF;
  END IF;

  -- Role validity (only if roleId is being changed)
  IF p_data ? 'roleId' AND p_data->>'roleId' IS NOT NULL THEN
    v_role_id := (p_data->>'roleId')::BIGINT;
    IF NOT EXISTS (SELECT 1 FROM role WHERE id = v_role_id AND is_active = true) THEN
      RAISE EXCEPTION 'fn_user_update: role not found or inactive';
    END IF;
  END IF;

  -- isActive validation + self-protection on suspend
  IF p_data ? 'isActive' AND p_data->>'isActive' IS NOT NULL THEN
    v_is_active := (p_data->>'isActive')::BOOLEAN;
    IF v_is_active = false AND p_actor_id IS NOT NULL AND p_id = p_actor_id THEN
      RAISE EXCEPTION 'fn_user_update: cannot suspend your own account';
    END IF;
  END IF;

  UPDATE "user" SET
    email      = COALESCE(LOWER(p_data->>'email'),         email),
    first_name = COALESCE(p_data->>'firstName',            first_name),
    last_name  = COALESCE(p_data->>'lastName',             last_name),
    role_id    = COALESCE((p_data->>'roleId')::BIGINT,     role_id),
    is_active  = COALESCE((p_data->>'isActive')::BOOLEAN,  is_active),
    updated_by = p_actor_id,
    updated_at = CURRENT_TIMESTAMP
  WHERE id = p_id;

  SELECT fn_user_get_by_id(p_id) INTO v_result;
  RETURN v_result;
EXCEPTION
  WHEN OTHERS THEN
    RAISE EXCEPTION 'fn_user_update: %', SQLERRM;
END;
$$;

REVOKE ALL ON FUNCTION fn_user_update(BIGINT, JSONB, BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION fn_user_update(BIGINT, JSONB, BIGINT) TO neondb_owner;
COMMENT ON FUNCTION fn_user_update(BIGINT, JSONB, BIGINT) IS
  'R-PA2: partial COALESCE update of email/firstName/lastName/roleId/isActive. Self-protection blocks self-suspend. Used by /admin/users row actions (Suspend, Reactivate, Change role).';

-- ──────────────────────────────────────────────────────────────────────────
-- 2. fn_user_password_reset — admin reset
-- ──────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION fn_user_password_reset(
  p_id            BIGINT,
  p_password_hash TEXT,
  p_actor_id      BIGINT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
BEGIN
  IF p_id IS NULL THEN
    RAISE EXCEPTION 'fn_user_password_reset: p_id is required';
  END IF;
  IF p_password_hash IS NULL OR length(p_password_hash) = 0 THEN
    RAISE EXCEPTION 'fn_user_password_reset: passwordHash is required';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM "user" WHERE id = p_id AND is_active = true) THEN
    RAISE EXCEPTION 'fn_user_password_reset: user not found or inactive';
  END IF;

  -- Self-protection: admin must not reset own password via this carve-out
  -- (the actor flow is /auth/change-password — covered elsewhere).
  IF p_actor_id IS NOT NULL AND p_id = p_actor_id THEN
    RAISE EXCEPTION 'fn_user_password_reset: cannot reset your own password — use /auth/change-password';
  END IF;

  UPDATE "user" SET
    password_hash = p_password_hash,
    updated_by    = p_actor_id,
    updated_at    = CURRENT_TIMESTAMP
  WHERE id = p_id;

  RETURN jsonb_build_object(
    'success', true,
    'message', 'Password reset',
    'userId',  p_id
  );
EXCEPTION
  WHEN OTHERS THEN
    RAISE EXCEPTION 'fn_user_password_reset: %', SQLERRM;
END;
$$;

REVOKE ALL ON FUNCTION fn_user_password_reset(BIGINT, TEXT, BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION fn_user_password_reset(BIGINT, TEXT, BIGINT) TO neondb_owner;
COMMENT ON FUNCTION fn_user_password_reset(BIGINT, TEXT, BIGINT) IS
  'R-PA2: admin password reset. Controller hashes plaintext with bcrypt(12) before invoking. Self-reset blocked — actor uses /auth/change-password instead.';

INSERT INTO schema_migrations (version, description, applied_at)
VALUES (96, 'pa_user_admin_actions', CURRENT_TIMESTAMP)
ON CONFLICT (version) DO NOTHING;

COMMIT;

-- ============================================================================
-- ROLLBACK BEGIN
-- ============================================================================
-- Re-apply 001's fn_user_update body to drop the isActive branch + drop the
-- new fn_user_password_reset:
--   DROP FUNCTION IF EXISTS fn_user_password_reset(BIGINT, TEXT, BIGINT);
--   DELETE FROM schema_migrations WHERE version = 96;
-- ROLLBACK END
