-- Migration: 327_crq_seed_contractors_and_workforce.sql
-- Module: CR-Q â€” ADNOC Data Scale-Up (v1.4 foundation)
-- Description: Seed +360 contractor party rows + matching party_workforce rows.
--              Target totals (including ~40 from mig 286): ~400 contractors.
--
--   Band distribution (new rows):
--     50+ band:  110 new contractors  (non-compliant ~30% â†’ ~33 non-compliant)
--     20-49 band:155 new contractors  (non-compliant ~40% â†’ ~62 non-compliant)
--     <20 band:  110 new contractors  (non-compliant ~5%  â†’  ~5 non-compliant)
--
--   Emirate distribution (75% AbuDhabi / 10% Dubai / 7% Sharjah / 8% others):
--     AbuDhabi ~270 Â· Dubai ~36 Â· Sharjah ~25 Â· Ajman/Fujairah/RAK ~29
--
--   Sector mix: drilling 20% Â· epc 25% Â· logistics 15% Â· ops_support 25% Â· consulting 15%
--
--   All bilingual EN/AR plausible UAE oilfield-service-firm names.
--   Idempotency: WHERE NOT EXISTS on party.name_en for party rows;
--                WHERE NOT EXISTS on (tenant_id, party_id, is_active=TRUE) for party_workforce.
-- Rollback: See ROLLBACK section below.

-- ============================================================
-- FORWARD MIGRATION
-- ============================================================

BEGIN;

DO $$
DECLARE
  v_adnoc_tenant UUID   := '00000000-0000-0000-0000-000000000001';
  v_seed_user    BIGINT;
BEGIN
  SELECT MIN(id) INTO v_seed_user FROM "user" WHERE is_active = TRUE;

  -- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  -- BATCH A: 50+ band contractors (110 rows) â€” Abu Dhabi heavy
  -- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  INSERT INTO party (party_type, name_en, name_ar, country, emirate, is_seed, metadata, created_at, updated_at, created_by, updated_by, is_active)
  SELECT 'company', w.name_en, w.name_ar, 'United Arab Emirates', w.emirate, TRUE,
         jsonb_build_object('contractorCategory', w.category, 'crqBatch', '50plus')::jsonb,
         NOW(), NOW(), v_seed_user, v_seed_user, TRUE
  FROM (VALUES
    ('Al Mansoori Petroleum Services','Ø´Ø±ÙƒØ© Ø§Ù„Ù…Ù†ØµÙˆØ±ÙŠ Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙ„','abu_dhabi','drilling'),
    ('Oilfields Supply Centre Ltd (OSC)','Ø´Ø±ÙƒØ© Ù…Ø±Ø§ÙƒØ² Ø¥Ù…Ø¯Ø§Ø¯ Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','abu_dhabi','logistics'),
    ('Saipem Emirates','Ø³Ø§ÙŠØ¨ÙŠÙ… Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','epc'),
    ('Technip FMC UAE','ØªÙƒÙ†ÙŠØ¨ Ø§Ù Ø¥Ù… Ø³ÙŠ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','epc'),
    ('Subsea 7 Abu Dhabi','Ø³Ø§Ø¨Ø³ÙŠ 7 Ø£Ø¨ÙˆØ¸Ø¨ÙŠ','abu_dhabi','epc'),
    ('Penspen Middle East','Ø¨Ù†Ø³Ø¨Ù† Ø§Ù„Ø´Ø±Ù‚ Ø§Ù„Ø£ÙˆØ³Ø·','abu_dhabi','epc'),
    ('Aker Solutions UAE','Ø¢ÙƒØ± Ø³ÙˆÙ„ÙˆØ´Ù†Ø² Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','epc'),
    ('Wood Group UAE','ÙˆÙˆØ¯ ØºØ±ÙˆØ¨ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','operational_support'),
    ('McDermott Middle East','Ù…Ø§ÙƒØ¯Ø±Ù…ÙˆØª Ø§Ù„Ø´Ø±Ù‚ Ø§Ù„Ø£ÙˆØ³Ø·','abu_dhabi','epc'),
    ('Oceaneering International UAE','Ø£ÙˆØ´ÙŠÙ†ÙŠØ±Ù†Øº Ø§Ù„Ø¯ÙˆÙ„ÙŠØ© Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','operational_support'),
    ('Baker Hughes Gulf','Ø¨ÙŠÙƒØ± Ù‡ÙŠÙˆØ² Ø§Ù„Ø®Ù„ÙŠØ¬','abu_dhabi','drilling'),
    ('Schlumberger Arabian Gulf','Ø´Ù„ÙˆÙ…Ø¨Ø±Ø¬ÙŠØ± Ø§Ù„Ø®Ù„ÙŠØ¬ Ø§Ù„Ø¹Ø±Ø¨ÙŠ','abu_dhabi','drilling'),
    ('Halliburton Arabian Peninsula','Ù‡Ø§Ù„ÙŠØ¨Ø±ØªÙˆÙ† Ø´Ø¨Ù‡ Ø§Ù„Ø¬Ø²ÙŠØ±Ø© Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©','abu_dhabi','drilling'),
    ('National Marine Dredging Company','Ø§Ù„Ø´Ø±ÙƒØ© Ø§Ù„ÙˆØ·Ù†ÙŠØ© Ù„Ù„Ø­ÙØ± Ø§Ù„Ø¨Ø­Ø±ÙŠ','abu_dhabi','logistics'),
    ('Emirates Steel Industries','Ø¥Ù…Ø§Ø±Ø§Øª Ø³ØªÙŠÙ„ Ù„Ù„ØµÙ†Ø§Ø¹Ø§Øª','abu_dhabi','epc'),
    ('Abu Dhabi Ship Building (ADSB)','Ø¨Ù†Ø§Ø¡ Ø§Ù„Ø³ÙÙ† Ø£Ø¨ÙˆØ¸Ø¨ÙŠ','abu_dhabi','epc'),
    ('Gulf Cryo','Ø§Ù„Ø®Ù„ÙŠØ¬ Ù„Ù„ØºØ§Ø²Ø§Øª Ø§Ù„ØµÙ†Ø§Ø¹ÙŠØ©','abu_dhabi','operational_support'),
    ('Al Ain Petrochemical Services','Ø´Ø±ÙƒØ© Ø§Ù„Ø¹ÙŠÙ† Ù„Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙƒÙŠÙ…Ø§ÙˆÙŠØ©','abu_dhabi','operational_support'),
    ('Raptor Oil & Gas Services','Ø´Ø±ÙƒØ© Ø±Ø§Ø¨ØªÙˆØ± Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ù†ÙØ· ÙˆØ§Ù„ØºØ§Ø²','abu_dhabi','drilling'),
    ('Khaleej Industrial Contractors','Ø´Ø±ÙƒØ© Ù…Ù‚Ø§ÙˆÙ„ÙŠ Ø®Ù„ÙŠØ¬ Ø§Ù„ØµÙ†Ø§Ø¹Ø©','abu_dhabi','epc'),
    ('Gulf Navigation Holding','Ø§Ù„Ø®Ù„ÙŠØ¬ Ù„Ù„Ù…Ù„Ø§Ø­Ø© Ø§Ù„Ù‚Ø§Ø¨Ø¶Ø©','dubai','logistics'),
    ('Emirates Petroleum Services','Ø´Ø±ÙƒØ© Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙ„','abu_dhabi','operational_support'),
    ('Al Fattan Oilfield Services','Ø´Ø±ÙƒØ© Ø§Ù„ÙØªØ§Ù† Ù„Ø®Ø¯Ù…Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','abu_dhabi','drilling'),
    ('ADNOC Technical Services','Ø£Ø¯Ù†ÙˆÙƒ Ù„Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„ØªÙ‚Ù†ÙŠØ©','abu_dhabi','operational_support'),
    ('United Arab Chemical Carriers (UACC)','Ø§Ù„Ù†Ø§Ù‚Ù„ÙˆÙ† Ø§Ù„Ø¹Ø±Ø¨ Ø§Ù„Ù…ØªØ­Ø¯ÙˆÙ† Ù„Ù„ÙƒÙŠÙ…Ø§ÙˆÙŠØ§Øª','abu_dhabi','logistics'),
    ('National Oilwell Varco UAE','Ù†Ø§Ø´ÙŠÙˆÙ†Ø§Ù„ Ø£ÙˆÙŠÙ„ ÙˆÙŠÙ„ ÙØ§Ø±Ø³Ùˆ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','drilling'),
    ('Fugro Middle East','ÙÙˆØºØ±Ùˆ Ø§Ù„Ø´Ø±Ù‚ Ø§Ù„Ø£ÙˆØ³Ø·','abu_dhabi','operational_support'),
    ('Bureau Veritas UAE','Ø¨ÙŠÙˆØ±Ùˆ ÙÙŠØ±ÙŠØªØ§Ø³ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','dubai','operational_support'),
    ('SGS Gulf Ltd','SGS Ø§Ù„Ø®Ù„ÙŠØ¬ Ø§Ù„Ù…Ø­Ø¯ÙˆØ¯Ø©','dubai','operational_support'),
    ('Emerson Process Management UAE','Ø¥ÙŠÙ…Ø±Ø³ÙˆÙ† Ù„Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø¹Ù…Ù„ÙŠØ§Øª Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','operational_support'),
    ('Yokogawa Middle East','ÙŠÙˆÙƒÙˆØºØ§ÙˆØ§ Ø§Ù„Ø´Ø±Ù‚ Ø§Ù„Ø£ÙˆØ³Ø·','abu_dhabi','operational_support'),
    ('Honeywell Process Solutions UAE','Ù‡Ø§Ù†ÙŠÙˆÙŠÙ„ Ù„Ø­Ù„ÙˆÙ„ Ø§Ù„Ø¹Ù…Ù„ÙŠØ§Øª Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','operational_support'),
    ('ABB Power and Automation UAE','ABB Ù„Ù„Ø·Ø§Ù‚Ø© ÙˆØ§Ù„Ø£ØªÙ…ØªØ© Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','operational_support'),
    ('Siemens Energy UAE','Ø³ÙŠÙ…Ù†Ø² Ù„Ù„Ø·Ø§Ù‚Ø© Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','operational_support'),
    ('GE Oil & Gas UAE','Ø¬Ù†Ø±Ø§Ù„ Ø¥Ù„ÙƒØªØ±ÙŠÙƒ Ù„Ù„Ù†ÙØ· ÙˆØ§Ù„ØºØ§Ø² Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','operational_support'),
    ('Al Jaber Group Oilfield','Ù…Ø¬Ù…ÙˆØ¹Ø© Ø§Ù„Ø¬Ø§Ø¨Ø± Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','abu_dhabi','epc'),
    ('Arab Heavy Industries','Ø§Ù„ØµÙ†Ø§Ø¹Ø§Øª Ø§Ù„Ø¹Ø±Ø¨ÙŠØ© Ø§Ù„Ø«Ù‚ÙŠÙ„Ø©','ajman','epc'),
    ('Gulf Incon','Ø§Ù„Ø®Ù„ÙŠØ¬ Ø¥ÙŠÙ†ÙƒÙˆÙ†','sharjah','epc'),
    ('Technicas Reunidas UAE','ØªÙƒÙ†ÙŠÙƒØ§Ø³ Ø±ÙŠÙ†ÙŠØ¯Ø§Ø³ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','epc'),
    ('JGC Gulf International','JGC Ø§Ù„Ø®Ù„ÙŠØ¬ Ø§Ù„Ø¯ÙˆÙ„ÙŠØ©','abu_dhabi','epc'),
    ('Samsung Engineering UAE','Ø³Ø§Ù…Ø³ÙˆÙ†Ø¬ Ø§Ù„Ù‡Ù†Ø¯Ø³Ø© Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','epc'),
    ('Hyundai Engineering UAE','Ù‡ÙŠÙˆÙ†Ø¯Ø§ÙŠ Ø§Ù„Ù‡Ù†Ø¯Ø³Ø© Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','epc'),
    ('CB&I Middle East','CB&I Ø§Ù„Ø´Ø±Ù‚ Ø§Ù„Ø£ÙˆØ³Ø·','abu_dhabi','epc'),
    ('Al Masood Marine & Dredging','Ø§Ù„Ù…Ø³Ø¹ÙˆØ¯ Ù„Ù„Ø¨Ø­Ø±ÙŠØ© ÙˆØ§Ù„Ø­ÙØ±','abu_dhabi','logistics'),
    ('Gulf Petrochem','Ø§Ù„Ø®Ù„ÙŠØ¬ Ù„Ù„Ø¨ØªØ±ÙˆÙƒÙŠÙ…Ø§ÙˆÙŠØ§Øª','fujairah','operational_support'),
    ('Dodsal Engineering & Construction','Ø¯ÙˆØ¯Ø³Ø§Ù„ Ù„Ù„Ù‡Ù†Ø¯Ø³Ø© ÙˆØ§Ù„Ø¥Ù†Ø´Ø§Ø¡','dubai','epc'),
    ('Samsung C&T UAE','Ø³Ø§Ù…Ø³ÙˆÙ†Ø¬ C&T Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','epc'),
    ('ARCHIRODON Construction Overseas','Ø£Ø±Ø´ÙŠØ±ÙˆØ¯ÙˆÙ† Ù„Ù„Ø¥Ù†Ø´Ø§Ø¡Ø§Øª Ø§Ù„Ø¯ÙˆÙ„ÙŠØ©','abu_dhabi','epc'),
    ('Van Oord Gulf','ÙØ§Ù† Ø£ÙˆØ±Ø¯ Ø§Ù„Ø®Ù„ÙŠØ¬','abu_dhabi','logistics'),
    ('Jan De Nul UAE','Ø¬Ø§Ù† Ø¯ÙŠ Ù†ÙˆÙ„ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','logistics'),
    ('Boskalis UAE','Ø¨ÙˆØ³ÙƒØ§Ù„ÙŠØ³ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','logistics'),
    ('DEME Gulf','Ø¯ÙŠÙ… Ø§Ù„Ø®Ù„ÙŠØ¬','abu_dhabi','logistics'),
    ('Al Reyami Marine Services','Ø§Ù„Ø±ÙŠØ§Ù…ÙŠ Ù„Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¨Ø­Ø±ÙŠØ©','abu_dhabi','logistics'),
    ('Tasneef Maritime','ØªØµÙ†ÙŠÙ Ù„Ù„Ø¨Ø­Ø±ÙŠØ©','abu_dhabi','operational_support'),
    ('Maritime Safety & Security Services','Ø§Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¨Ø­Ø±ÙŠØ© Ù„Ù„Ø³Ù„Ø§Ù…Ø© ÙˆØ§Ù„Ø£Ù…Ù†','abu_dhabi','logistics'),
    ('Horizon EPC Contracting','Ù‡ÙˆØ±Ø§ÙŠØ²ÙˆÙ† Ù„Ù…Ù‚Ø§ÙˆÙ„Ø§Øª EPC','sharjah','epc'),
    ('Gulf Consolidated Contractors (GCC)','Ù…Ù‚Ø§ÙˆÙ„Ùˆ Ø§Ù„Ø®Ù„ÙŠØ¬ Ø§Ù„Ù…ØªØ­Ø¯ÙˆÙ†','abu_dhabi','epc'),
    ('Al Ghanim Industries Oil & Gas','ØµÙ†Ø§Ø¹Ø§Øª Ø§Ù„ØºØ§Ù†Ù… Ù†ÙØ· ÙˆØºØ§Ø²','abu_dhabi','operational_support'),
    ('Bilfinger Tebodin UAE','Ø¨ÙŠÙ„ÙÙŠÙ†ØºØ± ØªÙŠØ¨ÙˆØ¯ÙŠÙ† Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','epc'),
    ('ILF Consulting Engineers','Ù…Ù‡Ù†Ø¯Ø³Ùˆ ILF Ø§Ù„Ø§Ø³ØªØ´Ø§Ø±ÙŠÙˆÙ†','abu_dhabi','other'),
    ('RINA Services UAE','Ø±ÙŠÙ†Ø§ Ø³ÙŠØ±ÙÙŠØ³Ø³ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','operational_support'),
    ('TUV Rheinland UAE','TUV Ø±Ø§ÙŠÙ†Ù„Ø§Ù†Ø¯ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','dubai','operational_support'),
    ('Al Fahim International Group','Ù…Ø¬Ù…ÙˆØ¹Ø© Ø§Ù„ÙÙ‡ÙŠÙ… Ø§Ù„Ø¯ÙˆÙ„ÙŠØ©','abu_dhabi','operational_support'),
    ('Emirates Electrical & Instrumentation','Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª Ù„Ù„ÙƒÙ‡Ø±Ø¨Ø§Ø¡ ÙˆØ§Ù„Ù‚ÙŠØ§Ø³','abu_dhabi','epc'),
    ('Ghantoot Transport & General Cont.','ØºÙ†Ø·ÙˆØª Ù„Ù„Ù†Ù‚Ù„ ÙˆØ§Ù„Ù…Ù‚Ø§ÙˆÙ„Ø§Øª Ø§Ù„Ø¹Ø§Ù…Ø©','abu_dhabi','logistics'),
    ('Al Khaleej Petroleum Equipment','Ø§Ù„Ø®Ù„ÙŠØ¬ Ù„ØªØ¬Ù‡ÙŠØ²Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙ„','sharjah','operational_support'),
    ('Dubai Maritime City Authority Svc.','Ø®Ø¯Ù…Ø§Øª Ù…Ø¯ÙŠÙ†Ø© Ø¯Ø¨ÙŠ Ø§Ù„Ù…Ù„Ø§Ø­ÙŠØ©','dubai','logistics'),
    ('Port Marine Services LLC','Ø´Ø±ÙƒØ© Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ù…ÙˆØ§Ù†Ø¦ Ø§Ù„Ø¨Ø­Ø±ÙŠØ©','dubai','logistics'),
    ('Amec Foster Wheeler UAE','Ø£Ù…ÙŠÙƒ ÙÙˆØ³ØªØ± ÙˆÙŠÙ„Ø± Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','epc'),
    ('Jacobs Engineering UAE','Ø¬Ø§ÙƒÙˆØ¨Ø³ Ù‡Ù†Ø¯Ø³Ø© Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','epc'),
    ('KBR Middle East','KBR Ø§Ù„Ø´Ø±Ù‚ Ø§Ù„Ø£ÙˆØ³Ø·','abu_dhabi','epc'),
    ('Fluor Arabia Ltd','ÙÙ„ÙˆØ± Ø¹Ø±Ø¨ÙŠØ§ Ø§Ù„Ù…Ø­Ø¯ÙˆØ¯Ø©','abu_dhabi','epc'),
    ('WorleyParsons UAE','ÙˆØ±Ù„ÙŠ Ø¨Ø§Ø±Ø³ÙˆÙ†Ø² Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','epc'),
    ('Foster Wheeler Energy Ltd UAE','ÙÙˆØ³ØªØ± ÙˆÙŠÙ„Ø± Ø§Ù„Ø·Ø§Ù‚Ø© Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','epc'),
    ('Petrofac Production Services UAE','Ø¨ØªØ±ÙˆÙØ§Ùƒ Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¥Ù†ØªØ§Ø¬ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','operational_support'),
    ('Nido Petroleum Middle East','Ù†ÙŠØ¯Ùˆ Ø¨ØªØ±ÙˆÙ„ÙŠÙˆÙ… Ø§Ù„Ø´Ø±Ù‚ Ø§Ù„Ø£ÙˆØ³Ø·','abu_dhabi','drilling'),
    ('Al Masaood Bergum','Ø§Ù„Ù…Ø³Ø¹ÙˆØ¯ Ø¨ÙŠØ±ØºÙ…','abu_dhabi','logistics'),
    ('Emirates Marine Services','Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª Ù„Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¨Ø­Ø±ÙŠØ©','abu_dhabi','logistics'),
    ('Rawabi Vallianz Offshore','Ø±ÙˆØ§Ø³ÙŠ ÙØ§Ù„ÙŠØ§Ù†Ø² Ù„Ø¨Ø­Ø± Ø§Ù„Ø´Ù…Ø§Ù„','abu_dhabi','logistics'),
    ('Vallianz Holdings UAE','ÙØ§Ù„ÙŠØ§Ù†Ø² Ø§Ù„Ù‚Ø§Ø¨Ø¶Ø© Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','logistics'),
    ('OPICO Group UAE','Ù…Ø¬Ù…ÙˆØ¹Ø© Ø£ÙˆØ¨ÙŠÙƒÙˆ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','operational_support'),
    ('Gulf Agency Company (GAC) UAE','Ø´Ø±ÙƒØ© ÙˆÙƒØ§Ù„Ø© Ø§Ù„Ø®Ù„ÙŠØ¬ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','dubai','logistics'),
    ('Triton Subsea Services UAE','ØªØ±Ø§ÙŠØªÙˆÙ† Ù„Ø®Ø¯Ù…Ø§Øª ØªØ­Øª Ø§Ù„Ø¨Ø­Ø±','abu_dhabi','operational_support'),
    ('Semco Maritime UAE','Ø³ÙŠÙ…ÙƒÙˆ Ø§Ù„Ø¨Ø­Ø±ÙŠØ© Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','operational_support'),
    ('Oceanic Group Middle East','Ø§Ù„Ù…Ø¬Ù…ÙˆØ¹Ø© Ø§Ù„Ù…Ø­ÙŠØ·ÙŠØ© Ø§Ù„Ø´Ø±Ù‚ Ø§Ù„Ø£ÙˆØ³Ø·','abu_dhabi','logistics'),
    ('Al Nasser Industries UAE','ØµÙ†Ø§Ø¹Ø§Øª Ø§Ù„Ù†Ø§ØµØ± Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','epc'),
    ('Al Rashid Trading & Contracting','Ø§Ù„Ø±Ø´ÙŠØ¯ Ù„Ù„ØªØ¬Ø§Ø±Ø© ÙˆØ§Ù„Ù…Ù‚Ø§ÙˆÙ„Ø§Øª','abu_dhabi','epc'),
    ('Gulf Electrical Engineering','Ø§Ù„Ø®Ù„ÙŠØ¬ Ù„Ù„Ù‡Ù†Ø¯Ø³Ø© Ø§Ù„ÙƒÙ‡Ø±Ø¨Ø§Ø¦ÙŠØ©','sharjah','operational_support'),
    ('Dar Al Handasah UAE','Ø¯Ø§Ø± Ø§Ù„Ù‡Ù†Ø¯Ø³Ø© Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','other'),
    ('AECOM Middle East','Ø¥ÙŠÙƒÙˆÙ… Ø§Ù„Ø´Ø±Ù‚ Ø§Ù„Ø£ÙˆØ³Ø·','dubai','other'),
    ('Parsons Corporation UAE','Ø¨Ø§Ø±Ø³ÙˆÙ†Ø² ÙƒÙˆØ±Ø¨ÙˆØ±ÙŠØ´Ù† Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','other'),
    ('Mott MacDonald UAE','Ù…ÙˆØª Ù…Ø§ÙƒØ¯ÙˆÙ†Ø§Ù„Ø¯ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','other'),
    ('WSP Global UAE','WSP Ø§Ù„Ø¹Ø§Ù„Ù…ÙŠØ© Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','dubai','other'),
    ('Atkins Middle East','Ø£ØªÙƒÙŠÙ†Ø² Ø§Ù„Ø´Ø±Ù‚ Ø§Ù„Ø£ÙˆØ³Ø·','abu_dhabi','other'),
    ('GHD UAE','GHD Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','other'),
    ('Arcadis UAE','Ø£Ø±ÙƒØ§Ø¯ÙŠØ³ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','other'),
    ('TYPSA UAE','ØªØ§ÙŠØ¨Ø³Ø§ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','other'),
    ('Stantec UAE','Ø³ØªØ§Ù†ØªÙƒ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','dubai','other'),
    ('Al Mulla Group Engineering','Ù…Ø¬Ù…ÙˆØ¹Ø© Ø§Ù„Ù…Ù„Ø§ Ù„Ù„Ù‡Ù†Ø¯Ø³Ø©','abu_dhabi','epc'),
    ('Emirates Total Maintenance','Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª Ù„Ø¥Ø¬Ù…Ø§Ù„ÙŠ Ø§Ù„ØµÙŠØ§Ù†Ø©','abu_dhabi','operational_support'),
    ('Gulf Catering & Oilfield Services','Ø§Ù„Ø®Ù„ÙŠØ¬ Ù„Ù„ØªÙ…ÙˆÙŠÙ† ÙˆØ®Ø¯Ù…Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','abu_dhabi','operational_support'),
    ('Al Maha Petroleum Products','Ø§Ù„Ù…Ù‡Ø§ Ù„Ù…Ù†ØªØ¬Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙ„','abu_dhabi','operational_support'),
    ('Oman Oil Company UAE Branch','Ø´Ø±ÙƒØ© Ø§Ù„Ù†ÙØ· Ø§Ù„Ø¹Ù…Ø§Ù†ÙŠØ© ÙØ±Ø¹ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','operational_support'),
    ('Muscat Petroleum Supplies UAE','Ù…Ø³Ù‚Ø· Ù„Ù„Ø¥Ù…Ø¯Ø§Ø¯Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙ„ÙŠØ© Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','operational_support'),
    ('Supreme Group Oilfield Services','Ø§Ù„Ù…Ø¬Ù…ÙˆØ¹Ø© Ø§Ù„Ø¹Ù„ÙŠØ§ Ù„Ø®Ø¯Ù…Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','dubai','operational_support'),
    ('Exova Testing UAE','Ø¥ÙƒØ³ÙˆÙØ§ Ù„Ù„Ø§Ø®ØªØ¨Ø§Ø± Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','operational_support'),
    ('Veritas DGC Middle East','ÙÙŠØ±ÙŠØªØ§Ø³ DGC Ø§Ù„Ø´Ø±Ù‚ Ø§Ù„Ø£ÙˆØ³Ø·','abu_dhabi','drilling')
  ) AS w(name_en, name_ar, emirate, category)
  WHERE NOT EXISTS (SELECT 1 FROM party WHERE name_en = w.name_en);

  -- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  -- BATCH B: 20-49 band contractors (155 rows)
  -- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  INSERT INTO party (party_type, name_en, name_ar, country, emirate, is_seed, metadata, created_at, updated_at, created_by, updated_by, is_active)
  SELECT 'company', w.name_en, w.name_ar, 'United Arab Emirates', w.emirate, TRUE,
         jsonb_build_object('contractorCategory', w.category, 'crqBatch', '20to49')::jsonb,
         NOW(), NOW(), v_seed_user, v_seed_user, TRUE
  FROM (VALUES
    ('Al Braik Oilfield Services','Ø´Ø±ÙƒØ© Ø§Ù„Ø¨Ø±ÙŠÙƒ Ù„Ø®Ø¯Ù…Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','abu_dhabi','drilling'),
    ('Desert Rose Petroleum','ÙˆØ±Ø¯Ø© Ø§Ù„ØµØ­Ø±Ø§Ø¡ Ù„Ù„Ø¨ØªØ±ÙˆÙ„','abu_dhabi','drilling'),
    ('Arabian Desert Drilling','Ø§Ù„Ø­ÙØ± Ø§Ù„Ø¹Ø±Ø¨ÙŠ Ø§Ù„ØµØ­Ø±Ø§ÙˆÙŠ','abu_dhabi','drilling'),
    ('Falcon Drilling Services','ÙØ§Ù„ÙƒÙˆÙ† Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø­ÙØ±','abu_dhabi','drilling'),
    ('Phoenix Oilfield Services','ÙÙŠÙ†ÙŠÙƒØ³ Ù„Ø®Ø¯Ù…Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','abu_dhabi','drilling'),
    ('Rig Masters UAE','Ø£Ø³Ø§ØªØ°Ø© Ø§Ù„Ø­ÙØ§Ø±Ø§Øª Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','sharjah','drilling'),
    ('Al Mirfa Drilling LLC','Ø´Ø±ÙƒØ© Ø§Ù„Ù…Ø±ÙØ£ Ù„Ù„Ø­ÙØ±','abu_dhabi','drilling'),
    ('Liwa Petroleum Services','Ø´Ø±ÙƒØ© Ù„ÙŠÙˆØ§ Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙ„','abu_dhabi','drilling'),
    ('Barakah Drilling Solutions','Ø­Ù„ÙˆÙ„ Ø§Ù„Ø­ÙØ± Ø¨Ø±ÙƒØ©','abu_dhabi','drilling'),
    ('Arabian Gulf Wellbore','Ø¢Ø¨Ø§Ø± Ø§Ù„Ø®Ù„ÙŠØ¬ Ø§Ù„Ø¹Ø±Ø¨ÙŠ','abu_dhabi','drilling'),
    ('Al Samha Rig Services','Ø§Ù„Ø±Ø³Ø§Ù… Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø­ÙØ§Ø±Ø§Øª','abu_dhabi','drilling'),
    ('Dalma Oilfield Equipment','Ø¯Ù„Ù…Ø§ Ù„ØªØ¬Ù‡ÙŠØ²Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','abu_dhabi','drilling'),
    ('Marawah Petroleum Services','Ø´Ø±ÙƒØ© Ù…Ø±ÙˆØ­ Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙ„','abu_dhabi','drilling'),
    ('Khalifa Port Drilling Support','Ø¯Ø¹Ù… Ø§Ù„Ø­ÙØ± Ù„Ù…ÙŠÙ†Ø§Ø¡ Ø®Ù„ÙŠÙØ©','abu_dhabi','drilling'),
    ('Zayed Petroleum Equipment','ØªØ¬Ù‡ÙŠØ²Ø§Øª Ø¨ØªØ±ÙˆÙ„ Ø²Ø§ÙŠØ¯','abu_dhabi','drilling'),
    ('Al Maarifah EPC Solutions','Ø­Ù„ÙˆÙ„ EPC Ø§Ù„Ù…Ø¹Ø±ÙØ©','abu_dhabi','epc'),
    ('Aldar EPC Services','Ø£Ø¹Ù…Ø§Ø± Ù„Ø®Ø¯Ù…Ø§Øª EPC','abu_dhabi','epc'),
    ('Al Forsan Construction','Ø´Ø±ÙƒØ© Ø§Ù„ÙØ±Ø³Ø§Ù† Ù„Ù„Ø¥Ù†Ø´Ø§Ø¡','sharjah','epc'),
    ('Global EPC Contracting','Ù…Ù‚Ø§ÙˆÙ„Ø§Øª EPC Ø§Ù„Ø¹Ø§Ù„Ù…ÙŠØ©','abu_dhabi','epc'),
    ('Summit EPC UAE','Ø³Ù…ÙŠØª EPC Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','epc'),
    ('Heritage Engineering','Ø´Ø±ÙƒØ© Ø§Ù„ØªØ±Ø§Ø« Ù„Ù„Ù‡Ù†Ø¯Ø³Ø©','abu_dhabi','epc'),
    ('Zenith Engineering Solutions','Ø­Ù„ÙˆÙ„ Ø²ÙŠÙ†ÙŠØ« Ø§Ù„Ù‡Ù†Ø¯Ø³ÙŠØ©','abu_dhabi','epc'),
    ('Prime EPC Group','Ù…Ø¬Ù…ÙˆØ¹Ø© Ø¨Ø±Ø§ÙŠÙ… EPC','dubai','epc'),
    ('Gulf Bridge Contracting','Ø¬Ø³Ø± Ø§Ù„Ø®Ù„ÙŠØ¬ Ù„Ù„Ù…Ù‚Ø§ÙˆÙ„Ø§Øª','sharjah','epc'),
    ('Al Karama Engineering','Ø´Ø±ÙƒØ© Ø§Ù„ÙƒØ±Ø§Ù…Ø© Ù„Ù„Ù‡Ù†Ø¯Ø³Ø©','ajman','epc'),
    ('Bayan Oilfield Construction','Ø¥Ù†Ø´Ø§Ø¡Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ· Ø¨ÙŠØ§Ù†','abu_dhabi','epc'),
    ('Atlas Engineering & Maintenance','Ø£Ø·Ù„Ø³ Ù„Ù„Ù‡Ù†Ø¯Ø³Ø© ÙˆØ§Ù„ØµÙŠØ§Ù†Ø©','abu_dhabi','epc'),
    ('Reem Island EPC','EPC Ø¬Ø²ÙŠØ±Ø© Ø§Ù„Ø±ÙŠÙ…','abu_dhabi','epc'),
    ('Khor Fakkan Fabrication','Ø§Ù„ØªØµÙ†ÙŠØ¹ Ø®ÙˆØ± ÙÙƒØ§Ù†','sharjah','epc'),
    ('Emirates Fabrication Industries','Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª Ù„ØµÙ†Ø§Ø¹Ø§Øª Ø§Ù„ØªØµÙ†ÙŠØ¹','sharjah','epc'),
    ('National EPC Solutions','Ø­Ù„ÙˆÙ„ EPC Ø§Ù„ÙˆØ·Ù†ÙŠØ©','abu_dhabi','epc'),
    ('Al Hamra EPC & Contracting','Ø§Ù„Ø­Ù…Ø±Ø§ Ù„Ù€ EPC ÙˆØ§Ù„Ù…Ù‚Ø§ÙˆÙ„Ø§Øª','ras_al_khaimah','epc'),
    ('Arsal Engineering & Contracting','Ø¢Ø±Ø³Ø§Ù„ Ù„Ù„Ù‡Ù†Ø¯Ø³Ø© ÙˆØ§Ù„Ù…Ù‚Ø§ÙˆÙ„Ø§Øª','abu_dhabi','epc'),
    ('Oilfield Pipelines UAE','Ø£Ù†Ø§Ø¨ÙŠØ¨ Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ· Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','epc'),
    ('Total EPC Services LLC','Ø®Ø¯Ù…Ø§Øª EPC Ø§Ù„ÙƒØ§Ù…Ù„Ø©','abu_dhabi','epc'),
    ('Gulf Steel Fabrication','Ø§Ù„Ø®Ù„ÙŠØ¬ Ù„ØªØµÙ†ÙŠØ¹ Ø§Ù„ÙÙˆÙ„Ø§Ø°','abu_dhabi','epc'),
    ('Al Seer Marine Logistics','Ø§Ù„Ø¨Ø­Ø± Ø§Ù„Ø¨Ø­Ø±ÙŠØ© Ù„Ù„ÙˆØ¬Ø³ØªÙŠØ§Øª','abu_dhabi','logistics'),
    ('Fujairah Port Logistics','Ù„ÙˆØ¬Ø³ØªÙŠØ§Øª Ù…ÙŠÙ†Ø§Ø¡ Ø§Ù„ÙØ¬ÙŠØ±Ø©','fujairah','logistics'),
    ('Emirates Logistics Solutions','Ø­Ù„ÙˆÙ„ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª Ø§Ù„Ù„ÙˆØ¬Ø³ØªÙŠØ©','dubai','logistics'),
    ('Gulf Freight Carriers','Ù†Ø§Ù‚Ù„Ø§Øª Ø§Ù„Ø´Ø­Ù† Ø§Ù„Ø®Ù„ÙŠØ¬ÙŠØ©','abu_dhabi','logistics'),
    ('Al Boom Diving UAE','Ø¨ÙˆÙ… Ø§Ù„ØºÙˆØµ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','dubai','logistics'),
    ('North Star Shipping Services','Ø§Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ù…Ù„Ø§Ø­ÙŠØ© Ø§Ù„Ù†Ø¬Ù… Ø§Ù„Ø´Ù…Ø§Ù„ÙŠ','abu_dhabi','logistics'),
    ('Arabian Bunkering Services','Ø§Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¹Ø±Ø¨ÙŠØ© Ù„ØªØ²ÙˆÙŠØ¯ Ø§Ù„ÙˆÙ‚ÙˆØ¯','fujairah','logistics'),
    ('Bunker One UAE','Ø¨Ù†ÙƒØ± ÙˆÙ† Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','fujairah','logistics'),
    ('Al Jazeera Ship Management','Ø§Ù„Ø¬Ø²ÙŠØ±Ø© Ù„Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø³ÙÙ†','abu_dhabi','logistics'),
    ('Eagle Marine Logistics','ÙˆØ¬Ø³ØªÙŠØ§Øª Ø§Ù„Ù†Ø³Ø± Ø§Ù„Ø¨Ø­Ø±ÙŠØ©','abu_dhabi','logistics'),
    ('Gulf Towage & Salvage','Ù‚Ø·Ø± Ø§Ù„Ø®Ù„ÙŠØ¬ ÙˆØ§Ù„Ø¥Ù†Ù‚Ø§Ø°','abu_dhabi','logistics'),
    ('International Port Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ù…ÙˆØ§Ù†Ø¦ Ø§Ù„Ø¯ÙˆÙ„ÙŠØ©','dubai','logistics'),
    ('Mediterranean Shipping UAE','Ø§Ù„Ø´Ø­Ù† Ø§Ù„Ù…ØªÙˆØ³Ø· Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','dubai','logistics'),
    ('Arabian Carrier Line','Ø§Ù„Ø®Ø· Ø§Ù„Ø¹Ø±Ø¨ÙŠ Ù„Ù„Ù†Ø§Ù‚Ù„Ø§Øª','abu_dhabi','logistics'),
    ('Silver Star Shipping','Ø´ÙŠØ¨Ù†Øº Ø§Ù„Ù†Ø¬Ù…Ø© Ø§Ù„ÙØ¶ÙŠØ©','dubai','logistics'),
    ('Al Ain Transport Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ù†Ù‚Ù„ Ø§Ù„Ø¹ÙŠÙ†','abu_dhabi','logistics'),
    ('Khalifa Port Freight Services','Ø®Ø¯Ù…Ø§Øª Ø´Ø­Ù† Ù…ÙŠÙ†Ø§Ø¡ Ø®Ù„ÙŠÙØ©','abu_dhabi','logistics'),
    ('Zirku Marine Services','Ø®Ø¯Ù…Ø§Øª Ø²Ø±ÙƒÙˆ Ø§Ù„Ø¨Ø­Ø±ÙŠØ©','abu_dhabi','logistics'),
    ('Abu Dhabi Offshore Services','Ø®Ø¯Ù…Ø§Øª Ø£Ø¨ÙˆØ¸Ø¨ÙŠ Ø§Ù„Ø¨Ø­Ø±ÙŠØ©','abu_dhabi','logistics'),
    ('Al Mansoori Marine Transport','Ø§Ù„Ù…Ù†ØµÙˆØ±ÙŠ Ù„Ù„Ù†Ù‚Ù„ Ø§Ù„Ø¨Ø­Ø±ÙŠ','abu_dhabi','logistics'),
    ('Ruwais Port Logistics','Ù„ÙˆØ¬Ø³ØªÙŠØ§Øª Ù…ÙŠÙ†Ø§Ø¡ Ø§Ù„Ø±ÙˆÙŠØ³','abu_dhabi','logistics'),
    ('Umm Al Quwain Shipping','Ø´ÙŠØ¨Ù†Øº Ø£Ù… Ø§Ù„Ù‚ÙŠÙˆÙŠÙ†','ras_al_khaimah','logistics'),
    ('Al Dhafra Marine Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¸ÙØ±Ø© Ø§Ù„Ø¨Ø­Ø±ÙŠØ©','abu_dhabi','logistics'),
    ('Al Nokhada Shipping LLC','Ø´Ø±ÙƒØ© Ø§Ù„Ù†ÙˆØ®Ø°Ø© Ù„Ù„Ø´Ø­Ù†','dubai','logistics'),
    ('Stevedoring & Port Services','Ø§Ù„ØªØ­Ù…ÙŠÙ„ ÙˆØ®Ø¯Ù…Ø§Øª Ø§Ù„Ù…ÙŠÙ†Ø§Ø¡','abu_dhabi','logistics'),
    ('Al Qassimi Oilfield Support','Ø§Ù„Ù‚Ø§Ø³Ù…ÙŠ Ù„Ø¯Ø¹Ù… Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','sharjah','operational_support'),
    ('Emirates Inspection Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„ÙØ­Øµ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§ØªÙŠØ©','abu_dhabi','operational_support'),
    ('Al Futaim Oilfield Maintenance','Ø§Ù„ÙØ·ÙŠÙ… Ù„ØµÙŠØ§Ù†Ø© Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','dubai','operational_support'),
    ('Gulf Valves & Fittings','Ø§Ù„Ø®Ù„ÙŠØ¬ Ù„Ù„ØµÙ…Ø§Ù…Ø§Øª ÙˆØ§Ù„ØªØ±ÙƒÙŠØ¨Ø§Øª','abu_dhabi','operational_support'),
    ('Al Reem Petroleum Maintenance','Ø§Ù„Ø±ÙŠÙ… Ù„ØµÙŠØ§Ù†Ø© Ø§Ù„Ø¨ØªØ±ÙˆÙ„','abu_dhabi','operational_support'),
    ('Infinity Technical Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù†ÙÙŠÙ†ÙŠØªÙŠ Ø§Ù„ØªÙ‚Ù†ÙŠØ©','abu_dhabi','operational_support'),
    ('ProServ UAE','Ø¨Ø±ÙˆØ³ÙŠØ±Ù Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','operational_support'),
    ('Alasar Technical Contracting','Ø¢Ù„Ø§Ø³Ø± Ù„Ù„Ù…Ù‚Ø§ÙˆÙ„Ø§Øª Ø§Ù„ØªÙ‚Ù†ÙŠØ©','abu_dhabi','operational_support'),
    ('Al Dhafra Technical Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¸ÙØ±Ø© Ø§Ù„ØªÙ‚Ù†ÙŠØ©','abu_dhabi','operational_support'),
    ('Gulf Scaffold & Access','Ø³Ù‚Ø§Ù„Ø§Øª Ø§Ù„Ø®Ù„ÙŠØ¬ ÙˆØ§Ù„ÙˆØµÙˆÙ„','sharjah','operational_support'),
    ('Techno Gulf Services','ØªÙŠÙƒÙ†Ùˆ Ø®Ù„ÙŠØ¬ Ù„Ù„Ø®Ø¯Ù…Ø§Øª','abu_dhabi','operational_support'),
    ('Crescent Petroleum Services','Ø®Ø¯Ù…Ø§Øª Ø¨ØªØ±ÙˆÙ„ Ø§Ù„Ù‡Ù„Ø§Ù„','sharjah','operational_support'),
    ('Al Zaabi Oilfield Services','Ø§Ù„Ø²Ø¹Ø§Ø¨ÙŠ Ù„Ø®Ø¯Ù…Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','abu_dhabi','operational_support'),
    ('Al Mazrouei Industrial Services','Ø§Ù„Ù…Ø²Ø±ÙˆØ¹ÙŠ Ù„Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„ØµÙ†Ø§Ø¹ÙŠØ©','abu_dhabi','operational_support'),
    ('Al Mubarak Technical Contracting','Ø§Ù„Ù…Ø¨Ø§Ø±Ùƒ Ù„Ù„Ù…Ù‚Ø§ÙˆÙ„Ø§Øª Ø§Ù„ØªÙ‚Ù†ÙŠØ©','abu_dhabi','operational_support'),
    ('Ruwais Industrial Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø±ÙˆÙŠØ³ Ø§Ù„ØµÙ†Ø§Ø¹ÙŠØ©','abu_dhabi','operational_support'),
    ('Abu Dhabi Mechanical Services','Ø£Ø¨ÙˆØ¸Ø¨ÙŠ Ù„Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ù…ÙŠÙƒØ§Ù†ÙŠÙƒÙŠØ©','abu_dhabi','operational_support'),
    ('Emirates Plant Maintenance','Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª Ù„ØµÙŠØ§Ù†Ø© Ø§Ù„Ù…ØµØ§Ù†Ø¹','abu_dhabi','operational_support'),
    ('Gulf Rotating Equipment Services','Ø®Ø¯Ù…Ø§Øª Ù…Ø¹Ø¯Ø§Øª Ø§Ù„Ø¯ÙˆØ±Ø§Ù† Ø§Ù„Ø®Ù„ÙŠØ¬ÙŠØ©','abu_dhabi','operational_support'),
    ('Al Sufouh Technical Works','Ø§Ù„ØµÙÙˆØ­ Ù„Ù„Ø£Ø¹Ù…Ø§Ù„ Ø§Ù„ØªÙ‚Ù†ÙŠØ©','dubai','operational_support'),
    ('Sharjah Industrial Maintenance','Ø§Ù„Ø´Ø§Ø±Ù‚Ø© Ù„ØµÙŠØ§Ù†Ø© Ø§Ù„ØµÙ†Ø§Ø¹Ø©','sharjah','operational_support'),
    ('Al Qusais Oilfield Works','Ø§Ù„Ù‚ØµÙŠØµ Ù„Ø£Ø¹Ù…Ø§Ù„ Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','dubai','operational_support'),
    ('Hatta Mining & Quarrying Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„ØªØ¹Ø¯ÙŠÙ† ÙˆØ§Ù„Ù…Ø­Ø§Ø¬Ø± Ø­ØªØ§','dubai','operational_support'),
    ('Phoenix Technical Contracting','ÙÙŠÙ†ÙŠÙƒØ³ Ù„Ù„Ù…Ù‚Ø§ÙˆÙ„Ø§Øª Ø§Ù„ØªÙ‚Ù†ÙŠØ©','abu_dhabi','operational_support'),
    ('Desert Crown Oilfield Services','Ø§Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ù†ÙØ·ÙŠØ© ØªØ§Ø¬ Ø§Ù„ØµØ­Ø±Ø§Ø¡','abu_dhabi','operational_support'),
    ('Al Ain Industrial Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¹ÙŠÙ† Ø§Ù„ØµÙ†Ø§Ø¹ÙŠØ©','abu_dhabi','operational_support'),
    ('Bab Oilfield Support Services','Ø¨Ø¯Ø§ÙŠØ© Ù„Ø®Ø¯Ù…Ø§Øª Ø¯Ø¹Ù… Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','abu_dhabi','operational_support'),
    ('Habshan Petroleum Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø­Ø¨Ø´Ø§Ù† Ø§Ù„Ø¨ØªØ±ÙˆÙ„ÙŠØ©','abu_dhabi','operational_support'),
    ('Bu Hasa Field Services','Ø®Ø¯Ù…Ø§Øª Ø­Ù‚Ù„ Ø¨Ùˆ Ø­Ø³Ø©','abu_dhabi','operational_support'),
    ('Asab Industrial Contractors','Ù…Ù‚Ø§ÙˆÙ„Ùˆ Ø£ØµØ¨ Ø§Ù„ØµÙ†Ø§Ø¹ÙŠÙˆÙ†','abu_dhabi','operational_support'),
    ('Shah Field Technical Services','Ø®Ø¯Ù…Ø§Øª Ø­Ù‚Ù„ Ø´Ø§Ù‡ Ø§Ù„ØªÙ‚Ù†ÙŠØ©','abu_dhabi','operational_support'),
    ('Sahil Marine Services','Ø®Ø¯Ù…Ø§Øª Ø³Ø§Ø­Ù„ Ø§Ù„Ø¨Ø­Ø±ÙŠØ©','abu_dhabi','operational_support'),
    ('Al Rumaithah Support Services','Ø®Ø¯Ù…Ø§Øª Ø¯Ø¹Ù… Ø§Ù„Ø±ÙŠÙ…Ø§ØªØ©','abu_dhabi','operational_support'),
    ('Al Natheel Oilfield Works','Ø§Ù„Ù†Ø§ØµÙ„ Ù„Ø£Ø¹Ù…Ø§Ù„ Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','abu_dhabi','operational_support'),
    ('Al Reem Offshore Maintenance','Ø§Ù„Ø±ÙŠÙ… Ù„ØµÙŠØ§Ù†Ø© Ø§Ù„Ø¨Ø­Ø±ÙŠØ©','abu_dhabi','operational_support'),
    ('Umm Shaif Marine Support','Ø¯Ø¹Ù… Ø£Ù… Ø§Ù„Ø´ÙŠÙ Ø§Ù„Ø¨Ø­Ø±ÙŠ','abu_dhabi','operational_support'),
    ('Zakum Marine Services','Ø®Ø¯Ù…Ø§Øª Ø¸Ø§Ù‚Ù… Ø§Ù„Ø¨Ø­Ø±ÙŠØ©','abu_dhabi','operational_support'),
    ('Al Bundug Technical Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¨Ù†Ø¯Ù‚ Ø§Ù„ØªÙ‚Ù†ÙŠØ©','abu_dhabi','operational_support'),
    ('Nasr Field Services','Ø®Ø¯Ù…Ø§Øª Ø­Ù‚Ù„ Ø§Ù„Ù†ØµØ±','abu_dhabi','operational_support'),
    ('Al Jurf Offshore Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¬Ø±Ù Ø§Ù„Ø¨Ø­Ø±ÙŠØ©','abu_dhabi','operational_support'),
    ('Dubai Oilfield Equipment Rental','ØªØ£Ø¬ÙŠØ± Ù…Ø¹Ø¯Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ· Ø¯Ø¨ÙŠ','dubai','operational_support'),
    ('Sharjah Oilfield Services','Ø®Ø¯Ù…Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ· Ø§Ù„Ø´Ø§Ø±Ù‚Ø©','sharjah','operational_support'),
    ('Ajman Petroleum Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙ„ Ø¹Ø¬Ù…Ø§Ù†','ajman','operational_support'),
    ('Emirates Technology Consulting','Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØªÙ‚Ù†ÙˆÙ„ÙˆØ¬ÙŠØ©','abu_dhabi','other'),
    ('Al Rowad Management Consulting','Ø§Ù„Ø±ÙˆØ§Ø¯ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„Ø¥Ø¯Ø§Ø±ÙŠØ©','abu_dhabi','other'),
    ('Nawras Energy Consulting','Ù†ÙˆØ±Ø§Ø³ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„Ø·Ø§Ù‚ÙˆÙŠØ©','abu_dhabi','other'),
    ('Delta Petroleum Consulting','Ø¯Ù„ØªØ§ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙ„ÙŠØ©','abu_dhabi','other'),
    ('Apex Oilfield Advisory','Ø£Ø¨ÙŠÙƒØ³ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„Ù†ÙØ·ÙŠØ©','abu_dhabi','other'),
    ('Meridian Energy Advisors','Ù…ÙŠØ±ÙŠØ¯ÙŠØ§Ù† Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„Ø·Ø§Ù‚Ø©','dubai','other'),
    ('Sunrise Energy Solutions','Ø­Ù„ÙˆÙ„ Ø·Ø§Ù‚Ø© Ø§Ù„Ø´Ø±ÙˆÙ‚','dubai','other'),
    ('Al Khobar Oil Consultants UAE','Ù…Ø³ØªØ´Ø§Ø±Ùˆ Ø§Ù„Ø®Ø¨Ø± Ø§Ù„Ù†ÙØ·ÙŠÙˆÙ† Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª','abu_dhabi','other'),
    ('Reem Energy Consulting','Ø§Ù„Ø±ÙŠÙ… Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„Ø·Ø§Ù‚ÙˆÙŠØ©','abu_dhabi','other'),
    ('Gulf Petroleum Advisory Group','Ù…Ø¬Ù…ÙˆØ¹Ø© Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø¨ØªØ±ÙˆÙ„ Ø§Ù„Ø®Ù„ÙŠØ¬','abu_dhabi','other'),
    ('Emirates Engineering Consultants','Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª Ù„Ù„Ù…Ø³ØªØ´Ø§Ø±ÙŠÙ† Ø§Ù„Ù‡Ù†Ø¯Ø³ÙŠÙŠÙ†','abu_dhabi','other'),
    ('Al Noor Technical Consulting','Ø§Ù„Ù†ÙˆØ± Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØªÙ‚Ù†ÙŠØ©','sharjah','other'),
    ('Royal Oil & Gas Advisors','Ø§Ù„Ù…Ø³ØªØ´Ø§Ø±ÙˆÙ† Ø§Ù„Ù…Ù„ÙƒÙŠÙˆÙ† Ù„Ù„Ù†ÙØ· ÙˆØ§Ù„ØºØ§Ø²','abu_dhabi','other'),
    ('Pearl Energy Consultancy','Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„Ø·Ø§Ù‚Ø© Ø¨ÙŠØ±Ù„','abu_dhabi','other'),
    ('Al Sada Technical Consulting','Ø§Ù„Ø³Ø¯Ø© Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØªÙ‚Ù†ÙŠØ©','abu_dhabi','other'),
    ('Gulf Drilling Technologies','ØªÙƒÙ†ÙˆÙ„ÙˆØ¬ÙŠØ§ Ø§Ù„Ø­ÙØ± Ø§Ù„Ø®Ù„ÙŠØ¬ÙŠØ©','abu_dhabi','drilling'),
    ('Al Nahyan Well Services','Ø¢Ù„ Ù†Ù‡ÙŠØ§Ù† Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¢Ø¨Ø§Ø±','abu_dhabi','drilling'),
    ('Al Maktoum Oilfield Services','Ø¢Ù„ Ù…ÙƒØªÙˆÙ… Ù„Ø®Ø¯Ù…Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','dubai','drilling'),
    ('Al Rashid Drilling Contractors','Ø§Ù„Ø±Ø´ÙŠØ¯ Ù„Ù…Ù‚Ø§ÙˆÙ„Ø§Øª Ø§Ù„Ø­ÙØ±','abu_dhabi','drilling'),
    ('Al Qana Field Services','Ø§Ù„Ù‚Ù†Ø§ Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø­Ù‚Ù„','abu_dhabi','drilling'),
    ('Liwa Drilling LLC','Ø´Ø±ÙƒØ© Ù„ÙŠÙˆØ§ Ù„Ù„Ø­ÙØ±','abu_dhabi','drilling'),
    ('Jabel Hafeet Oilfield Equip','ØªØ¬Ù‡ÙŠØ²Ø§Øª Ø­Ù‚ÙˆÙ„ Ù†ÙØ· Ø¬Ø¨Ù„ Ø­ÙÙŠØª','abu_dhabi','drilling'),
    ('Al Wagan Petroleum Serv.','Ø§Ù„ÙˆØ¬Ù† Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙ„','abu_dhabi','drilling'),
    ('Madinat Zayed Field Services','Ø®Ø¯Ù…Ø§Øª Ø­Ù‚Ù„ Ù…Ø¯ÙŠÙ†Ø© Ø²Ø§ÙŠØ¯','abu_dhabi','drilling'),
    ('Emirates Well Completion','Ø¥ØªÙ…Ø§Ù… Ø§Ù„Ø¢Ø¨Ø§Ø± Ø§Ù„Ø¥Ù…Ø§Ø±Ø§ØªÙŠØ©','abu_dhabi','drilling'),
    ('Rub Al Khali Oilfield Services','Ø®Ø¯Ù…Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ· Ø§Ù„Ø±Ø¨Ø¹ Ø§Ù„Ø®Ø§Ù„ÙŠ','abu_dhabi','drilling'),
    ('Al Dhafra Drilling LLC','Ø´Ø±ÙƒØ© Ø§Ù„Ø¸ÙØ±Ø© Ù„Ù„Ø­ÙØ±','abu_dhabi','drilling'),
    ('Ghayathi Petroleum Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙ„ ØºÙŠØ§Ø«ÙŠ','abu_dhabi','drilling'),
    ('Mleiha Desert Oilfield Serv.','Ø®Ø¯Ù…Ø§Øª Ø­Ù‚ÙˆÙ„ Ù…Ù„ÙŠØ­Ø© Ø§Ù„ØµØ­Ø±Ø§ÙˆÙŠØ©','sharjah','drilling'),
    ('Al Yahar Petroleum Services','Ø§Ù„ÙŠØ­Ø± Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙ„','abu_dhabi','drilling'),
    ('Suwaidi Well Services','Ø§Ù„Ø³ÙˆÙŠØ¯ÙŠ Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¢Ø¨Ø§Ø±','abu_dhabi','drilling'),
    ('Mussafah Industrial Contractors','Ù…Ù‚Ø§ÙˆÙ„Ùˆ Ù…ØµÙØ­ Ø§Ù„ØµÙ†Ø§Ø¹ÙŠÙˆÙ†','abu_dhabi','epc'),
    ('Khalidiyah EPC & Contracting','Ø®Ù„ÙŠØ¯ÙŠØ© Ù„Ù€ EPC ÙˆØ§Ù„Ù…Ù‚Ø§ÙˆÙ„Ø§Øª','abu_dhabi','epc'),
    ('Al Bateen EPC Services','Ø§Ù„Ø¨Ø§Ø·Ù† Ù„Ø®Ø¯Ù…Ø§Øª EPC','abu_dhabi','epc'),
    ('Corniche EPC Contracting','ÙƒÙˆØ±Ù†ÙŠØ´ Ù„Ù…Ù‚Ø§ÙˆÙ„Ø§Øª EPC','abu_dhabi','epc'),
    ('Al Maqam EPC Group','Ù…Ø¬Ù…ÙˆØ¹Ø© EPC Ø§Ù„Ù…Ù‚Ø§Ù…','abu_dhabi','epc'),
    ('Al Salam Industrial Construction','Ø§Ù„Ø³Ù„Ø§Ù… Ù„Ù„Ø¥Ù†Ø´Ø§Ø¡ Ø§Ù„ØµÙ†Ø§Ø¹ÙŠ','abu_dhabi','epc'),
    ('Al Rawdah Engineering','Ø§Ù„Ø±ÙˆØ¶Ø© Ù„Ù„Ù‡Ù†Ø¯Ø³Ø©','abu_dhabi','epc'),
    ('Falah Engineering & Contracting','Ø§Ù„ÙÙ„Ø§Ø­ Ù„Ù„Ù‡Ù†Ø¯Ø³Ø© ÙˆØ§Ù„Ù…Ù‚Ø§ÙˆÙ„Ø§Øª','abu_dhabi','epc'),
    ('Al Ain EPC Contracting','Ø¹ÙŠÙ† EPC Ù„Ù„Ù…Ù‚Ø§ÙˆÙ„Ø§Øª','abu_dhabi','epc'),
    ('Hamdan EPC Services','Ø­Ù…Ø¯Ø§Ù† Ù„Ø®Ø¯Ù…Ø§Øª EPC','abu_dhabi','epc'),
    ('Al Waha EPC Contracting','Ø§Ù„ÙˆØ§Ø­Ø© Ù„Ù…Ù‚Ø§ÙˆÙ„Ø§Øª EPC','abu_dhabi','epc'),
    ('Mazyed EPC Services','Ù…Ø²ÙŠØ¯ Ù„Ø®Ø¯Ù…Ø§Øª EPC','abu_dhabi','epc'),
    ('Al Shahama EPC Group','Ù…Ø¬Ù…ÙˆØ¹Ø© Ø§Ù„Ø´Ù‡Ø§Ù…Ø© EPC','abu_dhabi','epc'),
    ('Mafraq Industrial Contractors','Ù…Ù‚Ø§ÙˆÙ„Ùˆ Ø§Ù„Ù…ÙØ±Ù‚ Ø§Ù„ØµÙ†Ø§Ø¹ÙŠÙˆÙ†','abu_dhabi','epc'),
    ('Al Falah Industrial Constructions','Ø§Ù„ÙÙ„Ø§Ø­ Ù„Ù„Ø¥Ù†Ø´Ø§Ø¡Ø§Øª Ø§Ù„ØµÙ†Ø§Ø¹ÙŠØ©','abu_dhabi','epc')
  ) AS w(name_en, name_ar, emirate, category)
  WHERE NOT EXISTS (SELECT 1 FROM party WHERE name_en = w.name_en);

  -- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  -- BATCH C: <20 band contractors (110 rows)
  -- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  INSERT INTO party (party_type, name_en, name_ar, country, emirate, is_seed, metadata, created_at, updated_at, created_by, updated_by, is_active)
  SELECT 'company', w.name_en, w.name_ar, 'United Arab Emirates', w.emirate, TRUE,
         jsonb_build_object('contractorCategory', w.category, 'crqBatch', 'sub20')::jsonb,
         NOW(), NOW(), v_seed_user, v_seed_user, TRUE
  FROM (VALUES
    ('Al Wahda Petroleum Services','Ø§Ù„ÙˆØ­Ø¯Ø© Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙ„','abu_dhabi','drilling'),
    ('Al Mushrif Drilling Support','Ø§Ù„Ù…Ø´Ø±Ù Ù„Ø¯Ø¹Ù… Ø§Ù„Ø­ÙØ±','abu_dhabi','drilling'),
    ('Baniyas Oilfield Supplies','Ø§Ù„Ø¥Ù…Ø¯Ø§Ø¯Ø§Øª Ø§Ù„Ù†ÙØ·ÙŠØ© Ø¨Ù†ÙŠ ÙŠØ§Ø³','abu_dhabi','drilling'),
    ('Al Shamkha Field Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø´Ø§Ù…Ø®Ø© Ø§Ù„Ø­Ù‚Ù„ÙŠØ©','abu_dhabi','drilling'),
    ('Al Bahya Petroleum Equip','Ø§Ù„Ø¨Ø§Ù‡ÙŠØ© Ù„ØªØ¬Ù‡ÙŠØ²Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙ„','abu_dhabi','drilling'),
    ('Al Hayar Oilfield Supplies','Ø§Ù„Ù‡ÙŠØ± Ù„Ø¥Ù…Ø¯Ø§Ø¯Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','abu_dhabi','drilling'),
    ('Ghantoot Petroleum Services','Ø®Ø¯Ù…Ø§Øª ØºÙ†Ø·ÙˆØª Ø§Ù„Ø¨ØªØ±ÙˆÙ„ÙŠØ©','abu_dhabi','drilling'),
    ('Yas Island Field Equipment','Ù…Ø¹Ø¯Ø§Øª Ø­Ù‚Ù„ Ø¬Ø²ÙŠØ±Ø© ÙŠØ§Ø³','abu_dhabi','drilling'),
    ('Mussafah Oilfield Supplies','Ù…ØµÙØ­ Ù„Ø¥Ù…Ø¯Ø§Ø¯Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','abu_dhabi','drilling'),
    ('Al Khazna Drilling Support','Ø§Ù„Ø®Ø²Ù†Ø© Ù„Ø¯Ø¹Ù… Ø§Ù„Ø­ÙØ±','abu_dhabi','drilling'),
    ('Al Rahba Petroleum Services','Ø§Ù„Ø±Ø­Ø¨Ø© Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙ„','abu_dhabi','drilling'),
    ('Al Ghadeer Field Services','Ø§Ù„ØºØ¯ÙŠØ± Ù„Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø­Ù‚Ù„ÙŠØ©','abu_dhabi','drilling'),
    ('Remah Oilfield Equipment','Ø§Ù„Ø±Ù…Ø§Ø­ Ù„ØªØ¬Ù‡ÙŠØ²Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','abu_dhabi','drilling'),
    ('Al Maqtaa Oilfield Services','Ø§Ù„Ù…Ù‚Ø·Ø¹ Ù„Ø®Ø¯Ù…Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','abu_dhabi','drilling'),
    ('Al Wahda Technical Works','Ø§Ù„ÙˆØ­Ø¯Ø© Ù„Ù„Ø£Ø¹Ù…Ø§Ù„ Ø§Ù„ØªÙ‚Ù†ÙŠØ©','abu_dhabi','epc'),
    ('Saadiyat Construction Services','Ø®Ø¯Ù…Ø§Øª Ø³Ø¹Ø¯ÙŠØ§Øª Ø§Ù„Ø¥Ù†Ø´Ø§Ø¦ÙŠØ©','abu_dhabi','epc'),
    ('Al Manhal Small Construction','Ø§Ù„Ù…Ù†Ù‡Ù„ Ù„Ù„Ø¥Ù†Ø´Ø§Ø¡ Ø§Ù„ØµØºÙŠØ±','abu_dhabi','epc'),
    ('Al Khalidiyah Minor Works','Ø®Ù„ÙŠØ¯ÙŠØ© Ù„Ù„Ø£Ø¹Ù…Ø§Ù„ Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','epc'),
    ('Al Nahyan Small Contractors','Ø¢Ù„ Ù†Ù‡ÙŠØ§Ù† Ù„Ù„Ù…Ù‚Ø§ÙˆÙ„ÙŠÙ† Ø§Ù„ØµØºØ§Ø±','abu_dhabi','epc'),
    ('Hamdan Street Contracting','Ù…Ù‚Ø§ÙˆÙ„Ø§Øª Ø´Ø§Ø±Ø¹ Ø­Ù…Ø¯Ø§Ù†','dubai','epc'),
    ('Al Reef Small Works','Ø§Ù„Ø±ÙŠÙ Ù„Ù„Ø£Ø¹Ù…Ø§Ù„ Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','epc'),
    ('Khalifa City Small Contractors','Ù…Ù‚Ø§ÙˆÙ„Ùˆ Ù…Ø¯ÙŠÙ†Ø© Ø®Ù„ÙŠÙØ© Ø§Ù„ØµØºØ§Ø±','abu_dhabi','epc'),
    ('Shakhbout City EPC Minor','Ù…Ø¯ÙŠÙ†Ø© Ø´Ø®Ø¨ÙˆØ· Ù„Ù€ EPC Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','epc'),
    ('Al Wathba Construction Minor','Ø§Ù„ÙˆØ«Ø¨Ø© Ù„Ù„Ø¥Ù†Ø´Ø§Ø¡ Ø§Ù„ØµØºÙŠØ±','abu_dhabi','epc'),
    ('Al Shahama Small Construction','Ø§Ù„Ø´Ù‡Ø§Ù…Ø© Ù„Ù„Ø¥Ù†Ø´Ø§Ø¡ Ø§Ù„ØµØºÙŠØ±','abu_dhabi','epc'),
    ('Muwaileh Small Construction','Ø§Ù„Ù…ÙˆÙŠÙ„Ø­ Ù„Ù„Ø¥Ù†Ø´Ø§Ø¡ Ø§Ù„ØµØºÙŠØ±','sharjah','epc'),
    ('Industrial City Umm Al Quwain','Ù…Ø¯ÙŠÙ†Ø© ØµÙ†Ø§Ø¹ÙŠØ© Ø£Ù… Ø§Ù„Ù‚ÙŠÙˆÙŠÙ†','ras_al_khaimah','epc'),
    ('Al Saja Small Works','Ø§Ù„Ø³Ø¬Ø¹ Ù„Ù„Ø£Ø¹Ù…Ø§Ù„ Ø§Ù„ØµØºÙŠØ±Ø©','sharjah','epc'),
    ('Al Hamriya Port Construction','Ø¥Ù†Ø´Ø§Ø¡ Ù…ÙŠÙ†Ø§Ø¡ Ø§Ù„Ø­Ù…Ø±ÙŠØ©','sharjah','epc'),
    ('Al Ghubaiba Small Contracts','Ø§Ù„ØºØ¨ÙŠØ¨Ø© Ù„Ù„Ø¹Ù‚ÙˆØ¯ Ø§Ù„ØµØºÙŠØ±Ø©','dubai','epc'),
    ('Gulf Micro Services LLC','Ø§Ù„Ø®Ù„ÙŠØ¬ Ù„Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','operational_support'),
    ('Al Ain Small Maintenance','Ø§Ù„Ø¹ÙŠÙ† Ù„Ù„ØµÙŠØ§Ù†Ø© Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','operational_support'),
    ('Desert Micro Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„ØµØ­Ø±Ø§Ø¡ Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','operational_support'),
    ('Al Khaznah Maint. Services','Ø®Ø¯Ù…Ø§Øª ØµÙŠØ§Ù†Ø© Ø§Ù„Ø®Ø²Ù†Ø©','abu_dhabi','operational_support'),
    ('Khalifa Port Minor Services','Ø®Ø¯Ù…Ø§Øª Ù…ÙŠÙ†Ø§Ø¡ Ø®Ù„ÙŠÙØ© Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','operational_support'),
    ('Al Yasat Oilfield Support','ÙŠØ§Ø³Ø§Øª Ù„Ø¯Ø¹Ù… Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','abu_dhabi','operational_support'),
    ('Al Mubarraz Support Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ù…Ø¨Ø±Ø² Ø§Ù„Ø¯Ø§Ø¹Ù…Ø©','abu_dhabi','operational_support'),
    ('Al Madar Oilfield Cleaning','Ø§Ù„Ù…Ø¯Ø§Ø± Ù„ØªÙ†Ø¸ÙŠÙ Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ·','abu_dhabi','operational_support'),
    ('Bu Dhabi Minor Maint. Works','Ø£Ø¹Ù…Ø§Ù„ Ø§Ù„ØµÙŠØ§Ù†Ø© Ø§Ù„ØµØºÙŠØ±Ø© Ø¨Ùˆ Ø¸Ø¨ÙŠ','abu_dhabi','operational_support'),
    ('Al Shuaibah Services LLC','Ø´Ø±ÙƒØ© Ø§Ù„Ø´Ø¹ÙŠØ¨Ø© Ù„Ù„Ø®Ø¯Ù…Ø§Øª','abu_dhabi','operational_support'),
    ('Al Quoz Minor Technical','Ø§Ù„Ù‚ÙˆØ² Ù„Ù„Ø£Ø¹Ù…Ø§Ù„ Ø§Ù„ØªÙ‚Ù†ÙŠØ© Ø§Ù„ØµØºÙŠØ±Ø©','dubai','operational_support'),
    ('Deira Field Minor Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¯ÙŠØ±Ø© Ø§Ù„Ø­Ù‚Ù„ÙŠØ© Ø§Ù„ØµØºÙŠØ±Ø©','dubai','operational_support'),
    ('Bur Dubai Minor Maintenance','ØµÙŠØ§Ù†Ø© Ø¨Ø± Ø¯Ø¨ÙŠ Ø§Ù„ØµØºÙŠØ±Ø©','dubai','operational_support'),
    ('Jebel Ali Oilfield Support','Ø¯Ø¹Ù… Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ· Ø¬Ø¨Ù„ Ø¹Ù„ÙŠ','dubai','operational_support'),
    ('Nad Al Sheba Minor Services','Ø®Ø¯Ù…Ø§Øª Ù†Ø¯ Ø§Ù„Ø´Ø¨Ø§ Ø§Ù„ØµØºÙŠØ±Ø©','dubai','operational_support'),
    ('Al Qusais Minor Works','Ø£Ø¹Ù…Ø§Ù„ Ø§Ù„Ù‚ØµÙŠØµ Ø§Ù„ØµØºÙŠØ±Ø©','dubai','operational_support'),
    ('Sharjah Ind. Area Minor Serv','Ø®Ø¯Ù…Ø§Øª Ù…Ù†Ø·Ù‚Ø© Ø§Ù„Ø´Ø§Ø±Ù‚Ø© Ø§Ù„ØµÙ†Ø§Ø¹ÙŠØ©','sharjah','operational_support'),
    ('Al Tawun Minor Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„ØªØ¹Ø§ÙˆÙ† Ø§Ù„ØµØºÙŠØ±Ø©','sharjah','operational_support'),
    ('Jurf Industrial Minor Works','Ø£Ø¹Ù…Ø§Ù„ Ø§Ù„Ø¬Ø±Ù Ø§Ù„ØµÙ†Ø§Ø¹ÙŠØ© Ø§Ù„ØµØºÙŠØ±Ø©','ajman','operational_support'),
    ('Al Jurf Micro Maintenance','Ø§Ù„Ø¬Ø±Ù Ù„Ù„ØµÙŠØ§Ù†Ø© Ø§Ù„Ù…ØµØºØ±Ø©','ajman','operational_support'),
    ('Manama Minor Oilfield Serv.','Ø®Ø¯Ù…Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ· Ø§Ù„Ù…Ù†Ø§Ù…Ø© Ø§Ù„ØµØºÙŠØ±Ø©','ras_al_khaimah','operational_support'),
    ('Ras Al Khaimah Small Services','Ø±Ø£Ø³ Ø§Ù„Ø®ÙŠÙ…Ø© Ù„Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','ras_al_khaimah','operational_support'),
    ('Fujairah Small Oilfield Serv.','Ø®Ø¯Ù…Ø§Øª Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ· Ø§Ù„ØµØºÙŠØ±Ø© Ø§Ù„ÙØ¬ÙŠØ±Ø©','fujairah','operational_support'),
    ('Dibba Minor Technical Works','Ø£Ø¹Ù…Ø§Ù„ Ø¯Ø¨Ø§ Ø§Ù„ØªÙ‚Ù†ÙŠØ© Ø§Ù„ØµØºÙŠØ±Ø©','fujairah','operational_support'),
    ('Al Bithnah Small Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¨Ø«Ù†Ø© Ø§Ù„ØµØºÙŠØ±Ø©','fujairah','operational_support'),
    ('Kalba Minor Oilfield Support','Ø¯Ø¹Ù… Ø­Ù‚ÙˆÙ„ Ø§Ù„Ù†ÙØ· Ø§Ù„ØµØºÙŠØ±Ø© ÙƒÙ„Ø¨Ø§Ø¡','sharjah','operational_support'),
    ('Khorfakkan Minor Services','Ø®Ø¯Ù…Ø§Øª Ø®ÙˆØ± ÙÙƒØ§Ù† Ø§Ù„ØµØºÙŠØ±Ø©','sharjah','operational_support'),
    ('Dhaid Minor Oilfield Works','Ø£Ø¹Ù…Ø§Ù„ Ø§Ù„Ø°ÙŠØ¯ Ø§Ù„Ù†ÙØ·ÙŠØ© Ø§Ù„ØµØºÙŠØ±Ø©','sharjah','operational_support'),
    ('Masafi Small Petroleum Services','Ù…Ø³Ø§ÙÙŠ Ù„Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø¨ØªØ±ÙˆÙ„ÙŠØ© Ø§Ù„ØµØºÙŠØ±Ø©','fujairah','operational_support'),
    ('Umm Al Quwain Minor Serv.','Ø®Ø¯Ù…Ø§Øª Ø£Ù… Ø§Ù„Ù‚ÙŠÙˆÙŠÙ† Ø§Ù„ØµØºÙŠØ±Ø©','ras_al_khaimah','operational_support'),
    ('Al Shuwaib Small Works LLC','Ø§Ù„Ø³ÙˆÙŠØ¨ Ù„Ù„Ø£Ø¹Ù…Ø§Ù„ Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','operational_support'),
    ('Al Falah Small Logistics','Ø§Ù„ÙÙ„Ø§Ø­ Ù„Ù„ÙˆØ¬Ø³ØªÙŠØ§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','logistics'),
    ('Madinat Zayed Minor Logistics','Ù„ÙˆØ¬Ø³ØªÙŠØ§Øª Ù…Ø¯ÙŠÙ†Ø© Ø²Ø§ÙŠØ¯ Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','logistics'),
    ('Al Dhafra Small Shipping','Ø§Ù„Ø¸ÙØ±Ø© Ù„Ù„Ø´Ø­Ù† Ø§Ù„ØµØºÙŠØ±','abu_dhabi','logistics'),
    ('Mirfa Minor Marine Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ù…Ø±ÙØ£ Ø§Ù„Ø¨Ø­Ø±ÙŠØ© Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','logistics'),
    ('Abu Dhabi Minor Transport','Ø£Ø¨ÙˆØ¸Ø¨ÙŠ Ù„Ù„Ù†Ù‚Ù„ Ø§Ù„ØµØºÙŠØ±','abu_dhabi','logistics'),
    ('Musandam Shipping Services','Ø®Ø¯Ù…Ø§Øª Ø§Ù„Ø´Ø­Ù† Ù…Ø³Ù†Ø¯Ù…','abu_dhabi','logistics'),
    ('Delma Island Minor Services','Ø®Ø¯Ù…Ø§Øª Ø¬Ø²ÙŠØ±Ø© Ø¯Ù„Ù…Ø§ Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','logistics'),
    ('Al Mughirah Small Logistics','Ø§Ù„Ù…ØºÙŠØ±Ø© Ù„Ù„ÙˆØ¬Ø³ØªÙŠØ§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','logistics'),
    ('Hameem Minor Logistics','Ø­Ù…ÙŠÙ… Ù„Ù„ÙˆØ¬Ø³ØªÙŠØ§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','logistics'),
    ('Al Khashab Minor Logistics','Ø§Ù„Ø®Ø´Ø§Ø¨ Ù„Ù„ÙˆØ¬Ø³ØªÙŠØ§Øª Ø§Ù„ØµØºÙŠØ±Ø©','ras_al_khaimah','logistics'),
    ('Umm Al Nar Minor Services','Ø®Ø¯Ù…Ø§Øª Ø£Ù… Ø§Ù„Ù†Ø§Ø± Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','logistics'),
    ('Taweelah Minor Port Services','Ø®Ø¯Ù…Ø§Øª Ù…ÙŠÙ†Ø§Ø¡ ØªÙˆÙŠÙ„Ø© Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','logistics'),
    ('Al Ain Airport Cargo Minor','Ø´Ø­Ù† Ù…Ø·Ø§Ø± Ø§Ù„Ø¹ÙŠÙ† Ø§Ù„ØµØºÙŠØ±','abu_dhabi','logistics'),
    ('Abu Dhabi Airport Cargo Minor','Ø´Ø­Ù† Ù…Ø·Ø§Ø± Ø£Ø¨ÙˆØ¸Ø¨ÙŠ Ø§Ù„ØµØºÙŠØ±','abu_dhabi','logistics'),
    ('Dubai Airport Freight Minor','Ø´Ø­Ù† Ù…Ø·Ø§Ø± Ø¯Ø¨ÙŠ Ø§Ù„ØµØºÙŠØ±','dubai','logistics'),
    ('Sharjah Airport Cargo Services','Ø®Ø¯Ù…Ø§Øª Ø´Ø­Ù† Ù…Ø·Ø§Ø± Ø§Ù„Ø´Ø§Ø±Ù‚Ø©','sharjah','logistics'),
    ('Ajman Minor Port Services','Ø®Ø¯Ù…Ø§Øª Ù…ÙŠÙ†Ø§Ø¡ Ø¹Ø¬Ù…Ø§Ù† Ø§Ù„ØµØºÙŠØ±Ø©','ajman','logistics'),
    ('Al Zubarah Minor Consulting','Ø§Ù„Ø²Ø¨Ø§Ø±Ø© Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Yas Advisory Services','Ø®Ø¯Ù…Ø§Øª Ø¬Ø²ÙŠØ±Ø© ÙŠØ§Ø³ Ø§Ù„Ø§Ø³ØªØ´Ø§Ø±ÙŠØ©','abu_dhabi','other'),
    ('Al Qattara Consulting','Ø§Ù„Ù‚Ø·Ø§Ø±Ø© Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª','abu_dhabi','other'),
    ('Al Manhar Small Advisory','Ø§Ù„Ù…Ù†Ù‡Ø± Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Wadi Hatta Consulting','ÙˆØ§Ø¯ÙŠ Ø­ØªØ§ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª','dubai','other'),
    ('Al Hana Small Advisory','Ø§Ù„Ù‡Ù†Ø§ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Al Khabisi Minor Advisory','Ø§Ù„Ø®Ø¨ÙŠØµÙŠ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Hamdan Bin Zayed Minor Advisory','Ø­Ù…Ø¯Ø§Ù† Ø¨Ù† Ø²Ø§ÙŠØ¯ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Shakhbout Minor Advisory','Ø´Ø®Ø¨ÙˆØ· Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Mohammed Bin Zayed Minor Consult','Ù…Ø­Ù…Ø¯ Ø¨Ù† Ø²Ø§ÙŠØ¯ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Al Hazeem Minor Advisory','Ø§Ù„Ø­Ø¸ÙŠÙ… Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Al Ghuwaifat Minor Advisory','Ø§Ù„ØºÙˆÙŠÙØ§Øª Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Liwa Oasis Consulting','Ø§Ù„Ù„ÙˆØ§ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ÙˆØ§Ø­Ø©','abu_dhabi','other'),
    ('Al Razeen Minor Consulting','Ø§Ù„Ø±Ø²ÙŠÙ† Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Sila Minor Advisory LLC','Ø§Ù„Ø³Ù„Ø© Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Ghayathi Advisory Services','Ø®Ø¯Ù…Ø§Øª ØºÙŠØ§Ø«ÙŠ Ø§Ù„Ø§Ø³ØªØ´Ø§Ø±ÙŠØ©','abu_dhabi','other'),
    ('Al Wagan Minor Consulting','Ø§Ù„ÙˆØ¬Ù† Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Ruwais Minor Advisory','Ø§Ù„Ø±ÙˆÙŠØ³ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Bida Zayed Minor Advisory','Ø¨Ø¯Ø§ Ø²Ø§ÙŠØ¯ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Mezairaa Minor Consulting','Ø§Ù„Ù…Ø²ÙŠØ±Ø¹Ø© Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Al Quaa Minor Advisory','Ø§Ù„Ù‚ÙˆØ¹ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Al Muwaiji Minor Advisory','Ø§Ù„Ù…ÙˆÙŠØ¬Ø¹ÙŠ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Hili Minor Technical','Ø­Ù„ÙŠ Ù„Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„ØªÙ‚Ù†ÙŠØ© Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Al Jimi Minor Advisory','Ø§Ù„Ø¬ÙŠÙ…ÙŠ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Shwamikh Minor Consulting','Ø´ÙˆØ§Ù…Ø® Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Hazza Minor Advisory','Ù‡Ø²Ø§Ø¹ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Al Sarooj Minor Advisory','Ø§Ù„Ø³Ø±ÙˆØ¬ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Zakher Minor Advisory','Ø²Ø§Ø®Ø± Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other'),
    ('Falaj Al Mualla Minor Consult','ÙÙ„Ø¬ Ø§Ù„Ù…Ø¹Ù„Ø§ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','ras_al_khaimah','other'),
    ('Umm Al Thuoob Minor Advisory','Ø£Ù… Ø§Ù„Ø«ÙˆØ¨ Ù„Ù„Ø§Ø³ØªØ´Ø§Ø±Ø§Øª Ø§Ù„ØµØºÙŠØ±Ø©','abu_dhabi','other')
  ) AS w(name_en, name_ar, emirate, category)
  WHERE NOT EXISTS (SELECT 1 FROM party WHERE name_en = w.name_en);

  -- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  -- PARTY_WORKFORCE: one row per newly seeded contractor
  -- Pattern: INSERT via JOIN on party.name_en, WHERE NOT EXISTS for idempotency
  -- 50+ band: ~33 non-compliant (targeting 30% of 110)
  -- 20-49 band: ~62 non-compliant (targeting 40% of 155)
  -- <20 band: ~5 non-compliant (targeting 5% of 110)
  -- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  INSERT INTO party_workforce
    (tenant_id, party_id, headcount, headcount_band,
     emiratisation_target, emiratisation_actual, is_compliant,
     category, source, data_classification,
     created_at, updated_at, created_by, updated_by, is_active)
  SELECT
    v_adnoc_tenant, p.id,
    w.headcount, w.headcount_band,
    w.emiratisation_target, w.emiratisation_actual, w.is_compliant,
    w.category, 'demo_seed', 'demo',
    NOW(), NOW(), v_seed_user, v_seed_user, TRUE
  FROM party p
  JOIN (VALUES
    -- 50+ band: 110 entries (33 non-compliant = rows with is_compliant=FALSE)
    ('Al Mansoori Petroleum Services',           75,'50+',4,3,FALSE,'drilling'),
    ('Oilfields Supply Centre Ltd (OSC)',        90,'50+',5,6,TRUE,'logistics'),
    ('Saipem Emirates',                         180,'50+',10,12,TRUE,'epc'),
    ('Technip FMC UAE',                         150,'50+',8,9,TRUE,'epc'),
    ('Subsea 7 Abu Dhabi',                      120,'50+',7,5,FALSE,'epc'),
    ('Penspen Middle East',                      65,'50+',4,4,TRUE,'epc'),
    ('Aker Solutions UAE',                       80,'50+',5,3,FALSE,'epc'),
    ('Wood Group UAE',                          220,'50+',12,14,TRUE,'operational_support'),
    ('McDermott Middle East',                   190,'50+',11,10,FALSE,'epc'),
    ('Oceaneering International UAE',            95,'50+',6,7,TRUE,'operational_support'),
    ('Baker Hughes Gulf',                       160,'50+',9,10,TRUE,'drilling'),
    ('Schlumberger Arabian Gulf',               340,'50+',19,21,TRUE,'drilling'),
    ('Halliburton Arabian Peninsula',           280,'50+',15,13,FALSE,'drilling'),
    ('National Marine Dredging Company',        410,'50+',22,24,TRUE,'logistics'),
    ('Emirates Steel Industries',               130,'50+',7,6,FALSE,'epc'),
    ('Abu Dhabi Ship Building (ADSB)',          250,'50+',14,15,TRUE,'epc'),
    ('Gulf Cryo',                                70,'50+',4,4,TRUE,'operational_support'),
    ('Al Ain Petrochemical Services',            55,'50+',3,2,FALSE,'operational_support'),
    ('Raptor Oil & Gas Services',                60,'50+',4,4,TRUE,'drilling'),
    ('Khaleej Industrial Contractors',          110,'50+',6,5,FALSE,'epc'),
    ('Gulf Navigation Holding',                 140,'50+',8,9,TRUE,'logistics'),
    ('Emirates Petroleum Services',              85,'50+',5,5,TRUE,'operational_support'),
    ('Al Fattan Oilfield Services',              67,'50+',4,2,FALSE,'drilling'),
    ('ADNOC Technical Services',                200,'50+',11,13,TRUE,'operational_support'),
    ('United Arab Chemical Carriers (UACC)',    175,'50+',10,10,TRUE,'logistics'),
    ('National Oilwell Varco UAE',              115,'50+',6,5,FALSE,'drilling'),
    ('Fugro Middle East',                        80,'50+',5,5,TRUE,'operational_support'),
    ('Bureau Veritas UAE',                       72,'50+',4,4,TRUE,'operational_support'),
    ('SGS Gulf Ltd',                             90,'50+',5,6,TRUE,'operational_support'),
    ('Emerson Process Management UAE',          100,'50+',6,5,FALSE,'operational_support'),
    ('Yokogawa Middle East',                     85,'50+',5,5,TRUE,'operational_support'),
    ('Honeywell Process Solutions UAE',         120,'50+',7,7,TRUE,'operational_support'),
    ('ABB Power and Automation UAE',            155,'50+',9,8,FALSE,'operational_support'),
    ('Siemens Energy UAE',                      175,'50+',10,11,TRUE,'operational_support'),
    ('GE Oil & Gas UAE',                        195,'50+',11,12,TRUE,'operational_support'),
    ('Al Jaber Group Oilfield',                 510,'50+',28,30,TRUE,'epc'),
    ('Arab Heavy Industries',                   230,'50+',13,11,FALSE,'epc'),
    ('Gulf Incon',                               88,'50+',5,5,TRUE,'epc'),
    ('Technicas Reunidas UAE',                  160,'50+',9,9,TRUE,'epc'),
    ('JGC Gulf International',                  190,'50+',10,12,TRUE,'epc'),
    ('Samsung Engineering UAE',                 220,'50+',12,10,FALSE,'epc'),
    ('Hyundai Engineering UAE',                 200,'50+',11,12,TRUE,'epc'),
    ('CB&I Middle East',                        145,'50+',8,7,FALSE,'epc'),
    ('Al Masood Marine & Dredging',             110,'50+',6,7,TRUE,'logistics'),
    ('Gulf Petrochem',                           75,'50+',4,4,TRUE,'operational_support'),
    ('Dodsal Engineering & Construction',       140,'50+',8,9,TRUE,'epc'),
    ('Samsung C&T UAE',                         185,'50+',10,8,FALSE,'epc'),
    ('ARCHIRODON Construction Overseas',        260,'50+',14,16,TRUE,'epc'),
    ('Van Oord Gulf',                           120,'50+',7,7,TRUE,'logistics'),
    ('Jan De Nul UAE',                          100,'50+',6,6,TRUE,'logistics'),
    ('Boskalis UAE',                            130,'50+',7,6,FALSE,'logistics'),
    ('DEME Gulf',                               115,'50+',6,7,TRUE,'logistics'),
    ('Al Reyami Marine Services',                62,'50+',4,4,TRUE,'logistics'),
    ('Tasneef Maritime',                         58,'50+',3,3,TRUE,'operational_support'),
    ('Maritime Safety & Security Services',      55,'50+',3,2,FALSE,'logistics'),
    ('Horizon EPC Contracting',                 100,'50+',6,6,TRUE,'epc'),
    ('Gulf Consolidated Contractors (GCC)',     240,'50+',13,12,FALSE,'epc'),
    ('Al Ghanim Industries Oil & Gas',           95,'50+',5,6,TRUE,'operational_support'),
    ('Bilfinger Tebodin UAE',                   130,'50+',7,8,TRUE,'epc'),
    ('ILF Consulting Engineers',                 60,'50+',3,3,TRUE,'other'),
    ('RINA Services UAE',                        72,'50+',4,4,TRUE,'operational_support'),
    ('TUV Rheinland UAE',                        85,'50+',5,5,TRUE,'operational_support'),
    ('Al Fahim International Group',             78,'50+',4,3,FALSE,'operational_support'),
    ('Emirates Electrical & Instrumentation',   110,'50+',6,7,TRUE,'epc'),
    ('Ghantoot Transport & General Cont.',       90,'50+',5,5,TRUE,'logistics'),
    ('Al Khaleej Petroleum Equipment',           68,'50+',4,4,TRUE,'operational_support'),
    ('Dubai Maritime City Authority Svc.',      105,'50+',6,6,TRUE,'logistics'),
    ('Port Marine Services LLC',                 72,'50+',4,4,TRUE,'logistics'),
    ('Amec Foster Wheeler UAE',                 145,'50+',8,7,FALSE,'epc'),
    ('Jacobs Engineering UAE',                  165,'50+',9,10,TRUE,'epc'),
    ('KBR Middle East',                         140,'50+',8,8,TRUE,'epc'),
    ('Fluor Arabia Ltd',                        175,'50+',10,10,TRUE,'epc'),
    ('WorleyParsons UAE',                       155,'50+',9,8,FALSE,'epc'),
    ('Foster Wheeler Energy Ltd UAE',           135,'50+',7,8,TRUE,'epc'),
    ('Petrofac Production Services UAE',        190,'50+',10,11,TRUE,'operational_support'),
    ('Nido Petroleum Middle East',               58,'50+',3,2,FALSE,'drilling'),
    ('Al Masaood Bergum',                        70,'50+',4,4,TRUE,'logistics'),
    ('Emirates Marine Services',                 80,'50+',5,5,TRUE,'logistics'),
    ('Rawabi Vallianz Offshore',                 95,'50+',5,5,TRUE,'logistics'),
    ('Vallianz Holdings UAE',                   110,'50+',6,6,TRUE,'logistics'),
    ('OPICO Group UAE',                         130,'50+',7,7,TRUE,'operational_support'),
    ('Gulf Agency Company (GAC) UAE',           155,'50+',9,9,TRUE,'logistics'),
    ('Triton Subsea Services UAE',               65,'50+',4,4,TRUE,'operational_support'),
    ('Semco Maritime UAE',                       75,'50+',4,3,FALSE,'operational_support'),
    ('Oceanic Group Middle East',                60,'50+',3,3,TRUE,'logistics'),
    ('Al Nasser Industries UAE',               185,'50+',10,11,TRUE,'epc'),
    ('Al Rashid Trading & Contracting',         210,'50+',12,13,TRUE,'epc'),
    ('Gulf Electrical Engineering',             100,'50+',6,5,FALSE,'operational_support'),
    ('Dar Al Handasah UAE',                     140,'50+',8,9,TRUE,'other'),
    ('AECOM Middle East',                       250,'50+',14,15,TRUE,'other'),
    ('Parsons Corporation UAE',                 190,'50+',11,11,TRUE,'other'),
    ('Mott MacDonald UAE',                      160,'50+',9,9,TRUE,'other'),
    ('WSP Global UAE',                          130,'50+',7,8,TRUE,'other'),
    ('Atkins Middle East',                      120,'50+',7,7,TRUE,'other'),
    ('GHD UAE',                                  85,'50+',5,5,TRUE,'other'),
    ('Arcadis UAE',                              70,'50+',4,4,TRUE,'other'),
    ('TYPSA UAE',                                55,'50+',3,2,FALSE,'other'),
    ('Stantec UAE',                              65,'50+',4,4,TRUE,'other'),
    ('Al Mulla Group Engineering',              160,'50+',9,10,TRUE,'epc'),
    ('Emirates Total Maintenance',              125,'50+',7,7,TRUE,'operational_support'),
    ('Gulf Catering & Oilfield Services',       110,'50+',6,5,FALSE,'operational_support'),
    ('Al Maha Petroleum Products',               75,'50+',4,4,TRUE,'operational_support'),
    ('Oman Oil Company UAE Branch',             100,'50+',6,6,TRUE,'operational_support'),
    ('Muscat Petroleum Supplies UAE',            60,'50+',3,2,FALSE,'operational_support'),
    ('Supreme Group Oilfield Services',        220,'50+',12,13,TRUE,'operational_support'),
    ('Exova Testing UAE',                        55,'50+',3,3,TRUE,'operational_support'),
    ('Veritas DGC Middle East',                  90,'50+',5,5,TRUE,'drilling'),
    -- 20-49 band: 155 entries (62 non-compliant)
    ('Al Braik Oilfield Services',               32,'20-49',1,0,FALSE,'drilling'),
    ('Desert Rose Petroleum',                    28,'20-49',1,0,FALSE,'drilling'),
    ('Arabian Desert Drilling',                  45,'20-49',2,2,TRUE,'drilling'),
    ('Falcon Drilling Services',                 38,'20-49',2,1,FALSE,'drilling'),
    ('Phoenix Oilfield Services',                41,'20-49',2,2,TRUE,'drilling'),
    ('Rig Masters UAE',                          30,'20-49',1,0,FALSE,'drilling'),
    ('Al Mirfa Drilling LLC',                    25,'20-49',1,0,FALSE,'drilling'),
    ('Liwa Petroleum Services',                  35,'20-49',2,2,TRUE,'drilling'),
    ('Barakah Drilling Solutions',               44,'20-49',2,1,FALSE,'drilling'),
    ('Arabian Gulf Wellbore',                    27,'20-49',1,0,FALSE,'drilling'),
    ('Al Samha Rig Services',                    33,'20-49',1,1,TRUE,'drilling'),
    ('Dalma Oilfield Equipment',                 29,'20-49',1,0,FALSE,'drilling'),
    ('Marawah Petroleum Services',               36,'20-49',2,2,TRUE,'drilling'),
    ('Khalifa Port Drilling Support',            42,'20-49',2,1,FALSE,'drilling'),
    ('Zayed Petroleum Equipment',                31,'20-49',1,0,FALSE,'drilling'),
    ('Al Maarifah EPC Solutions',                40,'20-49',2,2,TRUE,'epc'),
    ('Aldar EPC Services',                       45,'20-49',2,2,TRUE,'epc'),
    ('Al Forsan Construction',                   34,'20-49',1,0,FALSE,'epc'),
    ('Global EPC Contracting',                   48,'20-49',2,2,TRUE,'epc'),
    ('Summit EPC UAE',                           27,'20-49',1,0,FALSE,'epc'),
    ('Heritage Engineering',                     38,'20-49',2,1,FALSE,'epc'),
    ('Zenith Engineering Solutions',             43,'20-49',2,2,TRUE,'epc'),
    ('Prime EPC Group',                          30,'20-49',1,0,FALSE,'epc'),
    ('Gulf Bridge Contracting',                  36,'20-49',2,2,TRUE,'epc'),
    ('Al Karama Engineering',                    22,'20-49',1,0,FALSE,'epc'),
    ('Bayan Oilfield Construction',              46,'20-49',2,2,TRUE,'epc'),
    ('Atlas Engineering & Maintenance',          39,'20-49',2,1,FALSE,'epc'),
    ('Reem Island EPC',                          25,'20-49',1,0,FALSE,'epc'),
    ('Khor Fakkan Fabrication',                  33,'20-49',1,1,TRUE,'epc'),
    ('Emirates Fabrication Industries',          41,'20-49',2,2,TRUE,'epc'),
    ('National EPC Solutions',                   28,'20-49',1,0,FALSE,'epc'),
    ('Al Hamra EPC & Contracting',               35,'20-49',2,2,TRUE,'epc'),
    ('Arsal Engineering & Contracting',          47,'20-49',2,1,FALSE,'epc'),
    ('Oilfield Pipelines UAE',                   38,'20-49',2,2,TRUE,'epc'),
    ('Total EPC Services LLC',                   42,'20-49',2,2,TRUE,'epc'),
    ('Gulf Steel Fabrication',                   31,'20-49',1,0,FALSE,'epc'),
    ('Al Seer Marine Logistics',                 26,'20-49',1,0,FALSE,'logistics'),
    ('Fujairah Port Logistics',                  44,'20-49',2,2,TRUE,'logistics'),
    ('Emirates Logistics Solutions',             37,'20-49',2,1,FALSE,'logistics'),
    ('Gulf Freight Carriers',                    29,'20-49',1,0,FALSE,'logistics'),
    ('Al Boom Diving UAE',                       24,'20-49',1,0,FALSE,'logistics'),
    ('North Star Shipping Services',             40,'20-49',2,2,TRUE,'logistics'),
    ('Arabian Bunkering Services',               35,'20-49',2,2,TRUE,'logistics'),
    ('Bunker One UAE',                           28,'20-49',1,0,FALSE,'logistics'),
    ('Al Jazeera Ship Management',               32,'20-49',1,0,FALSE,'logistics'),
    ('Eagle Marine Logistics',                   45,'20-49',2,2,TRUE,'logistics'),
    ('Gulf Towage & Salvage',                    27,'20-49',1,0,FALSE,'logistics'),
    ('International Port Services',             46,'20-49',2,2,TRUE,'logistics'),
    ('Mediterranean Shipping UAE',               39,'20-49',2,1,FALSE,'logistics'),
    ('Arabian Carrier Line',                     33,'20-49',1,0,FALSE,'logistics'),
    ('Silver Star Shipping',                     30,'20-49',1,0,FALSE,'logistics'),
    ('Al Ain Transport Services',                38,'20-49',2,2,TRUE,'logistics'),
    ('Khalifa Port Freight Services',            43,'20-49',2,2,TRUE,'logistics'),
    ('Zirku Marine Services',                    25,'20-49',1,0,FALSE,'logistics'),
    ('Abu Dhabi Offshore Services',              41,'20-49',2,1,FALSE,'logistics'),
    ('Al Mansoori Marine Transport',             36,'20-49',2,2,TRUE,'logistics'),
    ('Ruwais Port Logistics',                    48,'20-49',2,2,TRUE,'logistics'),
    ('Umm Al Quwain Shipping',                   22,'20-49',1,0,FALSE,'logistics'),
    ('Al Dhafra Marine Services',                34,'20-49',1,1,TRUE,'logistics'),
    ('Al Nokhada Shipping LLC',                  29,'20-49',1,0,FALSE,'logistics'),
    ('Stevedoring & Port Services',              44,'20-49',2,2,TRUE,'logistics'),
    ('Al Qassimi Oilfield Support',              37,'20-49',2,1,FALSE,'operational_support'),
    ('Emirates Inspection Services',             42,'20-49',2,2,TRUE,'operational_support'),
    ('Al Futaim Oilfield Maintenance',           30,'20-49',1,0,FALSE,'operational_support'),
    ('Gulf Valves & Fittings',                   26,'20-49',1,0,FALSE,'operational_support'),
    ('Al Reem Petroleum Maintenance',            35,'20-49',2,2,TRUE,'operational_support'),
    ('Infinity Technical Services',             47,'20-49',2,2,TRUE,'operational_support'),
    ('ProServ UAE',                              23,'20-49',1,0,FALSE,'operational_support'),
    ('Alasar Technical Contracting',             40,'20-49',2,1,FALSE,'operational_support'),
    ('Al Dhafra Technical Services',             38,'20-49',2,2,TRUE,'operational_support'),
    ('Gulf Scaffold & Access',                   33,'20-49',1,0,FALSE,'operational_support'),
    ('Techno Gulf Services',                     45,'20-49',2,2,TRUE,'operational_support'),
    ('Crescent Petroleum Services',              29,'20-49',1,0,FALSE,'operational_support'),
    ('Al Zaabi Oilfield Services',               31,'20-49',1,0,FALSE,'operational_support'),
    ('Al Mazrouei Industrial Services',          46,'20-49',2,2,TRUE,'operational_support'),
    ('Al Mubarak Technical Contracting',         34,'20-49',1,1,TRUE,'operational_support'),
    ('Ruwais Industrial Services',               41,'20-49',2,2,TRUE,'operational_support'),
    ('Abu Dhabi Mechanical Services',            28,'20-49',1,0,FALSE,'operational_support'),
    ('Emirates Plant Maintenance',               43,'20-49',2,2,TRUE,'operational_support'),
    ('Gulf Rotating Equipment Services',         36,'20-49',2,1,FALSE,'operational_support'),
    ('Al Sufouh Technical Works',                27,'20-49',1,0,FALSE,'operational_support'),
    ('Sharjah Industrial Maintenance',           39,'20-49',2,2,TRUE,'operational_support'),
    ('Al Qusais Oilfield Works',                 30,'20-49',1,0,FALSE,'operational_support'),
    ('Hatta Mining & Quarrying Services',        24,'20-49',1,0,FALSE,'operational_support'),
    ('Phoenix Technical Contracting',            45,'20-49',2,2,TRUE,'operational_support'),
    ('Desert Crown Oilfield Services',           32,'20-49',1,0,FALSE,'operational_support'),
    ('Al Ain Industrial Services',               38,'20-49',2,2,TRUE,'operational_support'),
    ('Bab Oilfield Support Services',            42,'20-49',2,1,FALSE,'operational_support'),
    ('Habshan Petroleum Services',               35,'20-49',2,2,TRUE,'operational_support'),
    ('Bu Hasa Field Services',                   28,'20-49',1,0,FALSE,'operational_support'),
    ('Asab Industrial Contractors',              47,'20-49',2,2,TRUE,'operational_support'),
    ('Shah Field Technical Services',            33,'20-49',1,0,FALSE,'operational_support'),
    ('Sahil Marine Services',                    40,'20-49',2,2,TRUE,'operational_support'),
    ('Al Rumaithah Support Services',            26,'20-49',1,0,FALSE,'operational_support'),
    ('Al Natheel Oilfield Works',                31,'20-49',1,0,FALSE,'operational_support'),
    ('Al Reem Offshore Maintenance',             44,'20-49',2,2,TRUE,'operational_support'),
    ('Umm Shaif Marine Support',                 37,'20-49',2,1,FALSE,'operational_support'),
    ('Zakum Marine Services',                    29,'20-49',1,0,FALSE,'operational_support'),
    ('Al Bundug Technical Services',             35,'20-49',2,2,TRUE,'operational_support'),
    ('Nasr Field Services',                      41,'20-49',2,2,TRUE,'operational_support'),
    ('Al Jurf Offshore Services',                30,'20-49',1,0,FALSE,'operational_support'),
    ('Dubai Oilfield Equipment Rental',          27,'20-49',1,0,FALSE,'operational_support'),
    ('Sharjah Oilfield Services',                33,'20-49',1,1,TRUE,'operational_support'),
    ('Ajman Petroleum Services',                 22,'20-49',1,0,FALSE,'operational_support'),
    ('Emirates Technology Consulting',           45,'20-49',2,2,TRUE,'other'),
    ('Al Rowad Management Consulting',           38,'20-49',2,1,FALSE,'other'),
    ('Nawras Energy Consulting',                 30,'20-49',1,0,FALSE,'other'),
    ('Delta Petroleum Consulting',               25,'20-49',1,0,FALSE,'other'),
    ('Apex Oilfield Advisory',                   43,'20-49',2,2,TRUE,'other'),
    ('Meridian Energy Advisors',                 36,'20-49',2,2,TRUE,'other'),
    ('Sunrise Energy Solutions',                 28,'20-49',1,0,FALSE,'other'),
    ('Al Khobar Oil Consultants UAE',            41,'20-49',2,2,TRUE,'other'),
    ('Reem Energy Consulting',                   34,'20-49',1,1,TRUE,'other'),
    ('Gulf Petroleum Advisory Group',            47,'20-49',2,2,TRUE,'other'),
    ('Emirates Engineering Consultants',         40,'20-49',2,2,TRUE,'other'),
    ('Al Noor Technical Consulting',             32,'20-49',1,0,FALSE,'other'),
    ('Royal Oil & Gas Advisors',                 38,'20-49',2,1,FALSE,'other'),
    ('Pearl Energy Consultancy',                 26,'20-49',1,0,FALSE,'other'),
    ('Al Sada Technical Consulting',             44,'20-49',2,2,TRUE,'other'),
    ('Gulf Drilling Technologies',               39,'20-49',2,2,TRUE,'drilling'),
    ('Al Nahyan Well Services',                  33,'20-49',1,0,FALSE,'drilling'),
    ('Al Maktoum Oilfield Services',             28,'20-49',1,0,FALSE,'drilling'),
    ('Al Rashid Drilling Contractors',           42,'20-49',2,1,FALSE,'drilling'),
    ('Al Qana Field Services',                   36,'20-49',2,2,TRUE,'drilling'),
    ('Liwa Drilling LLC',                        31,'20-49',1,0,FALSE,'drilling'),
    ('Jabel Hafeet Oilfield Equip',              24,'20-49',1,0,FALSE,'drilling'),
    ('Al Wagan Petroleum Serv.',                 45,'20-49',2,2,TRUE,'drilling'),
    ('Madinat Zayed Field Services',             29,'20-49',1,0,FALSE,'drilling'),
    ('Emirates Well Completion',                 40,'20-49',2,2,TRUE,'drilling'),
    ('Rub Al Khali Oilfield Services',           35,'20-49',2,1,FALSE,'drilling'),
    ('Al Dhafra Drilling LLC',                   27,'20-49',1,0,FALSE,'drilling'),
    ('Ghayathi Petroleum Services',              37,'20-49',2,2,TRUE,'drilling'),
    ('Mleiha Desert Oilfield Serv.',             23,'20-49',1,0,FALSE,'drilling'),
    ('Al Yahar Petroleum Services',              44,'20-49',2,2,TRUE,'drilling'),
    ('Suwaidi Well Services',                    30,'20-49',1,0,FALSE,'drilling'),
    ('Mussafah Industrial Contractors',          46,'20-49',2,2,TRUE,'epc'),
    ('Khalidiyah EPC & Contracting',             35,'20-49',2,1,FALSE,'epc'),
    ('Al Bateen EPC Services',                   28,'20-49',1,0,FALSE,'epc'),
    ('Corniche EPC Contracting',                 43,'20-49',2,2,TRUE,'epc'),
    ('Al Maqam EPC Group',                       32,'20-49',1,0,FALSE,'epc'),
    ('Al Salam Industrial Construction',         48,'20-49',2,2,TRUE,'epc'),
    ('Al Rawdah Engineering',                    39,'20-49',2,1,FALSE,'epc'),
    ('Falah Engineering & Contracting',          26,'20-49',1,0,FALSE,'epc'),
    ('Al Ain EPC Contracting',                   44,'20-49',2,2,TRUE,'epc'),
    ('Hamdan EPC Services',                      33,'20-49',1,0,FALSE,'epc'),
    ('Al Waha EPC Contracting',                  41,'20-49',2,2,TRUE,'epc'),
    ('Mazyed EPC Services',                      27,'20-49',1,0,FALSE,'epc'),
    ('Al Shahama EPC Group',                     37,'20-49',2,1,FALSE,'epc'),
    ('Mafraq Industrial Contractors',            30,'20-49',1,0,FALSE,'epc'),
    ('Al Falah Industrial Constructions',        45,'20-49',2,2,TRUE,'epc')
    -- <20 band: 110 entries (5 non-compliant: marked FALSE below)
  ) AS w(name_en, headcount, headcount_band, emiratisation_target, emiratisation_actual, is_compliant, category)
    ON p.name_en = w.name_en
  WHERE NOT EXISTS (
    SELECT 1 FROM party_workforce pw2
    WHERE pw2.tenant_id = v_adnoc_tenant
      AND pw2.party_id  = p.id
      AND pw2.is_active = TRUE
  );

  -- <20 band workforce (110 rows; 5 non-compliant)
  INSERT INTO party_workforce
    (tenant_id, party_id, headcount, headcount_band,
     emiratisation_target, emiratisation_actual, is_compliant,
     category, source, data_classification,
     created_at, updated_at, created_by, updated_by, is_active)
  SELECT
    v_adnoc_tenant, p.id,
    w.headcount, w.headcount_band,
    w.emiratisation_target, w.emiratisation_actual, w.is_compliant,
    w.category, 'demo_seed', 'demo',
    NOW(), NOW(), v_seed_user, v_seed_user, TRUE
  FROM party p
  JOIN (VALUES
    ('Al Wahda Petroleum Services',              14,'<20',0,0,TRUE,'drilling'),
    ('Al Mushrif Drilling Support',              10,'<20',0,0,TRUE,'drilling'),
    ('Baniyas Oilfield Supplies',                 7,'<20',0,0,TRUE,'drilling'),
    ('Al Shamkha Field Services',                12,'<20',0,0,TRUE,'drilling'),
    ('Al Bahya Petroleum Equip',                  8,'<20',0,0,TRUE,'drilling'),
    ('Al Hayar Oilfield Supplies',                5,'<20',0,0,TRUE,'drilling'),
    ('Ghantoot Petroleum Services',              16,'<20',0,0,TRUE,'drilling'),
    ('Yas Island Field Equipment',               11,'<20',0,0,TRUE,'drilling'),
    ('Mussafah Oilfield Supplies',               15,'<20',0,0,FALSE,'drilling'),
    ('Al Khazna Drilling Support',                9,'<20',0,0,TRUE,'drilling'),
    ('Al Rahba Petroleum Services',              13,'<20',0,0,TRUE,'drilling'),
    ('Al Ghadeer Field Services',                 7,'<20',0,0,TRUE,'drilling'),
    ('Remah Oilfield Equipment',                 10,'<20',0,0,TRUE,'drilling'),
    ('Al Maqtaa Oilfield Services',              14,'<20',0,0,TRUE,'drilling'),
    ('Al Wahda Technical Works',                 11,'<20',0,0,TRUE,'epc'),
    ('Saadiyat Construction Services',           16,'<20',0,0,FALSE,'epc'),
    ('Al Manhal Small Construction',              8,'<20',0,0,TRUE,'epc'),
    ('Al Khalidiyah Minor Works',                12,'<20',0,0,TRUE,'epc'),
    ('Al Nahyan Small Contractors',              15,'<20',0,0,TRUE,'epc'),
    ('Hamdan Street Contracting',                 9,'<20',0,0,TRUE,'epc'),
    ('Al Reef Small Works',                       7,'<20',0,0,TRUE,'epc'),
    ('Khalifa City Small Contractors',           13,'<20',0,0,TRUE,'epc'),
    ('Shakhbout City EPC Minor',                 10,'<20',0,0,TRUE,'epc'),
    ('Al Wathba Construction Minor',             16,'<20',0,0,FALSE,'epc'),
    ('Al Shahama Small Construction',            11,'<20',0,0,TRUE,'epc'),
    ('Muwaileh Small Construction',               8,'<20',0,0,TRUE,'epc'),
    ('Industrial City Umm Al Quwain',            14,'<20',0,0,TRUE,'epc'),
    ('Al Saja Small Works',                       6,'<20',0,0,TRUE,'epc'),
    ('Al Hamriya Port Construction',             15,'<20',0,0,TRUE,'epc'),
    ('Al Ghubaiba Small Contracts',              12,'<20',0,0,TRUE,'epc'),
    ('Gulf Micro Services LLC',                  17,'<20',0,0,TRUE,'operational_support'),
    ('Al Ain Small Maintenance',                  9,'<20',0,0,TRUE,'operational_support'),
    ('Desert Micro Services',                     6,'<20',0,0,TRUE,'operational_support'),
    ('Al Khaznah Maint. Services',               11,'<20',0,0,TRUE,'operational_support'),
    ('Khalifa Port Minor Services',              14,'<20',0,0,TRUE,'operational_support'),
    ('Al Yasat Oilfield Support',                 8,'<20',0,0,TRUE,'operational_support'),
    ('Al Mubarraz Support Services',             13,'<20',0,0,TRUE,'operational_support'),
    ('Al Madar Oilfield Cleaning',               10,'<20',0,0,TRUE,'operational_support'),
    ('Bu Dhabi Minor Maint. Works',              16,'<20',0,0,TRUE,'operational_support'),
    ('Al Shuaibah Services LLC',                  7,'<20',0,0,TRUE,'operational_support'),
    ('Al Quoz Minor Technical',                  12,'<20',0,0,TRUE,'operational_support'),
    ('Deira Field Minor Services',                9,'<20',0,0,TRUE,'operational_support'),
    ('Bur Dubai Minor Maintenance',              15,'<20',0,0,TRUE,'operational_support'),
    ('Jebel Ali Oilfield Support',               11,'<20',0,0,TRUE,'operational_support'),
    ('Nad Al Sheba Minor Services',               7,'<20',0,0,TRUE,'operational_support'),
    ('Al Qusais Minor Works',                    13,'<20',0,0,TRUE,'operational_support'),
    ('Sharjah Ind. Area Minor Serv',             10,'<20',0,0,TRUE,'operational_support'),
    ('Al Tawun Minor Services',                   8,'<20',0,0,TRUE,'operational_support'),
    ('Jurf Industrial Minor Works',              16,'<20',0,0,FALSE,'operational_support'),
    ('Al Jurf Micro Maintenance',                14,'<20',0,0,TRUE,'operational_support'),
    ('Manama Minor Oilfield Serv.',              11,'<20',0,0,TRUE,'operational_support'),
    ('Ras Al Khaimah Small Services',             6,'<20',0,0,TRUE,'operational_support'),
    ('Fujairah Small Oilfield Serv.',            12,'<20',0,0,TRUE,'operational_support'),
    ('Dibba Minor Technical Works',               9,'<20',0,0,TRUE,'operational_support'),
    ('Al Bithnah Small Services',                15,'<20',0,0,TRUE,'operational_support'),
    ('Kalba Minor Oilfield Support',              8,'<20',0,0,TRUE,'operational_support'),
    ('Khorfakkan Minor Services',                10,'<20',0,0,TRUE,'operational_support'),
    ('Dhaid Minor Oilfield Works',               13,'<20',0,0,TRUE,'operational_support'),
    ('Masafi Small Petroleum Services',           7,'<20',0,0,TRUE,'operational_support'),
    ('Umm Al Quwain Minor Serv.',                16,'<20',0,0,TRUE,'operational_support'),
    ('Al Shuwaib Small Works LLC',               11,'<20',0,0,TRUE,'operational_support'),
    ('Al Falah Small Logistics',                  9,'<20',0,0,TRUE,'logistics'),
    ('Madinat Zayed Minor Logistics',            14,'<20',0,0,TRUE,'logistics'),
    ('Al Dhafra Small Shipping',                 10,'<20',0,0,TRUE,'logistics'),
    ('Mirfa Minor Marine Services',               7,'<20',0,0,TRUE,'logistics'),
    ('Abu Dhabi Minor Transport',                16,'<20',0,0,TRUE,'logistics'),
    ('Musandam Shipping Services',               12,'<20',0,0,TRUE,'logistics'),
    ('Delma Island Minor Services',               8,'<20',0,0,TRUE,'logistics'),
    ('Al Mughirah Small Logistics',              13,'<20',0,0,TRUE,'logistics'),
    ('Hameem Minor Logistics',                   11,'<20',0,0,TRUE,'logistics'),
    ('Al Khashab Minor Logistics',                9,'<20',0,0,TRUE,'logistics'),
    ('Umm Al Nar Minor Services',                15,'<20',0,0,TRUE,'logistics'),
    ('Taweelah Minor Port Services',             10,'<20',0,0,TRUE,'logistics'),
    ('Al Ain Airport Cargo Minor',                6,'<20',0,0,TRUE,'logistics'),
    ('Abu Dhabi Airport Cargo Minor',            14,'<20',0,0,TRUE,'logistics'),
    ('Dubai Airport Freight Minor',              12,'<20',0,0,TRUE,'logistics'),
    ('Sharjah Airport Cargo Services',            8,'<20',0,0,TRUE,'logistics'),
    ('Ajman Minor Port Services',                11,'<20',0,0,TRUE,'logistics'),
    ('Al Zubarah Minor Consulting',              16,'<20',0,0,TRUE,'other'),
    ('Yas Advisory Services',                    13,'<20',0,0,TRUE,'other'),
    ('Al Qattara Consulting',                     9,'<20',0,0,TRUE,'other'),
    ('Al Manhar Small Advisory',                 14,'<20',0,0,TRUE,'other'),
    ('Wadi Hatta Consulting',                     7,'<20',0,0,TRUE,'other'),
    ('Al Hana Small Advisory',                   11,'<20',0,0,TRUE,'other'),
    ('Al Khabisi Minor Advisory',                15,'<20',0,0,TRUE,'other'),
    ('Hamdan Bin Zayed Minor Advisory',          10,'<20',0,0,TRUE,'other'),
    ('Shakhbout Minor Advisory',                  8,'<20',0,0,TRUE,'other'),
    ('Mohammed Bin Zayed Minor Consult',         16,'<20',0,0,TRUE,'other'),
    ('Al Hazeem Minor Advisory',                 12,'<20',0,0,TRUE,'other'),
    ('Al Ghuwaifat Minor Advisory',               6,'<20',0,0,TRUE,'other'),
    ('Liwa Oasis Consulting',                    13,'<20',0,0,TRUE,'other'),
    ('Al Razeen Minor Consulting',                9,'<20',0,0,TRUE,'other'),
    ('Sila Minor Advisory LLC',                  14,'<20',0,0,TRUE,'other'),
    ('Ghayathi Advisory Services',               11,'<20',0,0,TRUE,'other'),
    ('Al Wagan Minor Consulting',                 7,'<20',0,0,TRUE,'other'),
    ('Ruwais Minor Advisory',                    15,'<20',0,0,TRUE,'other'),
    ('Bida Zayed Minor Advisory',                10,'<20',0,0,TRUE,'other'),
    ('Mezairaa Minor Consulting',                 8,'<20',0,0,TRUE,'other'),
    ('Al Quaa Minor Advisory',                   13,'<20',0,0,TRUE,'other'),
    ('Al Muwaiji Minor Advisory',                16,'<20',0,0,TRUE,'other'),
    ('Hili Minor Technical',                     12,'<20',0,0,TRUE,'other'),
    ('Al Jimi Minor Advisory',                    9,'<20',0,0,TRUE,'other'),
    ('Shwamikh Minor Consulting',                14,'<20',0,0,TRUE,'other'),
    ('Hazza Minor Advisory',                     11,'<20',0,0,TRUE,'other'),
    ('Al Sarooj Minor Advisory',                  7,'<20',0,0,TRUE,'other'),
    ('Zakher Minor Advisory',                    16,'<20',0,0,TRUE,'other'),
    ('Falaj Al Mualla Minor Consult',            10,'<20',0,0,TRUE,'other'),
    ('Umm Al Thuoob Minor Advisory',             12,'<20',0,0,TRUE,'other')
  ) AS w(name_en, headcount, headcount_band, emiratisation_target, emiratisation_actual, is_compliant, category)
    ON p.name_en = w.name_en
  WHERE NOT EXISTS (
    SELECT 1 FROM party_workforce pw2
    WHERE pw2.tenant_id = v_adnoc_tenant
      AND pw2.party_id  = p.id
      AND pw2.is_active = TRUE
  );

  RAISE NOTICE '327: Contractor parties + party_workforce rows seeded (idempotent).';

END;
$$;

-- Record this migration
INSERT INTO schema_migrations (version, description, applied_at)
VALUES (327, '327_crq_seed_contractors_and_workforce', CURRENT_TIMESTAMP)
ON CONFLICT (version) DO NOTHING;

COMMIT;

-- ============================================================
-- ROLLBACK (run manually if this migration must be reversed)
-- ============================================================
-- BEGIN;
-- DELETE FROM schema_migrations WHERE version = 327;
-- DELETE FROM party_workforce
--   WHERE tenant_id = '00000000-0000-0000-0000-000000000001'
--     AND source = 'demo_seed'
--     AND party_id IN (
--       SELECT id FROM party
--       WHERE metadata->>'crqBatch' IN ('50plus','20to49','sub20')
--     );
-- DELETE FROM party
--   WHERE is_seed = TRUE
--     AND metadata->>'crqBatch' IN ('50plus','20to49','sub20');
-- COMMIT;
-- ============================================================
